//! Renders the standard, fully-commented `sai-cfg.yml` from interview [`Answers`].
//! The output is the canonical dummy config: every knob documented, the chosen values
//! filled in, everything else left as commented examples. `render` output is guaranteed
//! to parse back into [`crate::config::Config`] (see the round-trip tests).

use super::interview::Answers;
// Shared with runtime resolution so the two can never drift: the default ort model
// needs no explicit `duckdb.model_repo` override (it lives in its own HF repo), and
// e5-small's ONNX export repo is the same one `build_plan` resolves to.
use crate::config::{DEFAULT_MODEL_REPO, DEFAULT_ORT_MODEL};

/// Render a user-supplied scalar for YAML. Plain identifiers, paths, and URLs are
/// emitted raw (matching the hand-written style of the template); anything YAML could
/// misread — spaces, `#`, flow/indicator characters, quote characters, or values that
/// look like numbers/booleans — is double-quoted with escaping, so pathological
/// answers still produce a config that parses back to exactly what was typed.
fn yaml_scalar(value: &str) -> String {
    let safe_char = |c: char| c.is_ascii_alphanumeric() || "-_./:@+".contains(c);
    let looks_typed = value.parse::<f64>().is_ok()
        || matches!(
            value.to_ascii_lowercase().as_str(),
            "true" | "false" | "null" | "yes" | "no" | "on" | "off"
        );
    let plain =
        !value.is_empty() && value.chars().all(safe_char) && !value.ends_with(':') && !looks_typed;
    if plain {
        value.to_string()
    } else {
        format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
    }
}

/// HF repo the ort embedder should download a given model from. Most models live in
/// their own repo; e5-small's ONNX export lives in the Xenova mirror.
fn ort_model_repo_for(model: &str) -> String {
    if model.to_ascii_lowercase().contains("e5-small") {
        DEFAULT_MODEL_REPO.to_string()
    } else {
        model.to_string()
    }
}

/// Render the full commented config with the interview answers filled in.
pub fn render(a: &Answers) -> String {
    let mut y = String::with_capacity(8 * 1024);

    y.push_str(
        "# semanticastindexer configuration. Generated by `semanticastindexer init`.\n\
         #\n\
         # Controls what gets embedded and pushed to the selected vector backend (Qdrant or\n\
         # DuckDB). Loaded by default from `sai-cfg.yml` in the current directory (then\n\
         # `sai-cfg.yaml`, then the legacy `indexer.yaml`); override with `--config <path>`.\n\
         # CLI flags (--backend, --collection, --model, ...) take precedence over values here.\n\
         #\n\
         # These are sane GENERIC defaults: with the binary built `--features ort` you can\n\
         # index any project fully offline out of the box (local ONNX embedder + DuckDB).\n",
    );

    y.push_str(
        "# Vector backend: \"qdrant\" (default) or \"duckdb\". The CLI flag `--backend <name>`\n\
         # overrides this value. Qdrant uses Cloud server-side inference: set its URL in the\n\
         # `qdrant:` block below (or via the QDRANT_URL env var). The API KEY is a SECRET, read\n\
         # ONLY from the QDRANT_API_KEY environment variable — never put it in YAML. DuckDB embeds locally (via the\n\
         # `ort` or `ollama` embedder) and stores vectors in a DuckDB file with a VSS/HNSW\n\
         # index; it needs the binary built with `--features ort` / `--features ollama`\n\
         # (or `all`).\n",
    );
    y.push_str(&format!("backend: {}\n", yaml_scalar(&a.backend)));

    y.push_str(
        "# Embedder for the DuckDB backend (IGNORED by Qdrant, which embeds server-side):\n\
         #   ort     — local ONNX Runtime; downloads the model from `duckdb.model_repo` (default)\n\
         #   ollama  — remote Ollama HTTP server (see the `ollama:` block; `ollama.model` REQUIRED)\n\
         # CLI `--embedder <name>` overrides this. Default: ort.\n",
    );
    y.push_str(&format!("embedder: {}\n", yaml_scalar(&a.embedder)));

    y.push_str(
        "# Chunker — how each file is split into embeddable chunks. CLI `--chunker <name>` overrides.\n\
         # Left unset on purpose: the smart default picks the symbol-aware \"ast\" chunker for\n\
         # languages with AST support (ts/tsx/rs/go) when the binary was built with\n\
         # `--features ast` (or `all`), and the reliable \"lines\" chunker for everything else.\n\
         #\n\
         #   lines  — line-window chunker. ~MAX_LINES lines / `max_chunk_chars` chars per window\n\
         #            with a small overlap. No symbols. Always available.\n\
         #   ast    — tree-sitter, FUNCTION-ONLY (TS/TSX + Rust + Go). Emits ONE chunk per named\n\
         #            function at any depth. Oversized functions are line-split, keeping the\n\
         #            symbol. A file with no functions yields no chunks. Requires `--features ast`.\n\
         #\n\
         #   NOTE: comments are stripped BEFORE chunking.\n\
         # chunker: ast\n",
    );

    y.push_str(
        "# Max chunk size in CHARS — the size bound BOTH chunkers honor (a char approximation of\n\
         # the model's token window, ~4 chars/token; no tokenizer needed). When unset, it is\n\
         # defaulted by the embedder/model:\n\
         #   e5 / qdrant (512-token window)      → ~1400 chars  (keeps the historical behavior)\n\
         #   qwen / generic ollama (8K tokens)   → ~32000 chars (so whole functions fit)\n\
         # Set explicitly to override the model-aware default.\n\
         # max_chunk_chars: 1400\n\
         \n\
         # Embedding prefix policy. When unset, AUTO-DETECTED from `model`:\n\
         #   model contains \"e5\"   → e5    (passage: <t> / query: <t>)\n\
         #   model contains \"qwen\" → qwen  (bare passage; query wrapped: \"Instruct: …\\nQuery: <q>\")\n\
         #   otherwise             → none  (bare on both sides)\n\
         # Explicit values: e5 | qwen | none. Applied by BOTH local embedders AND the Qdrant\n\
         # Document path via one shared helper.\n\
         # prefix_style: e5\n\
         \n",
    );

    y.push_str(
        "# Target collection (Qdrant) / table (DuckDB) + the embedding model label. For Qdrant\n\
         # this must match the cluster's Inference tab. `vector_dim` MUST equal the embedder\n\
         # model's output dimensionality and is validated at runtime — a mismatch is a clear\n\
         # error.\n",
    );
    y.push_str(&format!("collection: {}\n", yaml_scalar(&a.collection)));
    y.push_str(&format!("model: {}\n", yaml_scalar(&a.model)));
    y.push_str(&format!("vector_dim: {}\n", a.vector_dim));

    // Qdrant block: an explicit URL is written; otherwise the env-var route is documented.
    y.push_str(
        "# Qdrant backend settings (only used when backend: qdrant). The API key is NOT here — it\n\
         # is read only from the QDRANT_API_KEY environment variable (a secret).\n",
    );
    match &a.qdrant_url {
        Some(url) => {
            y.push_str("qdrant:\n");
            y.push_str(
                "  # Qdrant cluster gRPC URL. The QDRANT_URL env var, if set, overrides this.\n",
            );
            y.push_str(&format!("  url: {}\n", yaml_scalar(url)));
        }
        None => y.push_str(
            "qdrant:\n\
             # Qdrant cluster gRPC URL. The QDRANT_URL env var, if set, overrides this.\n\
             # url: https://<cluster-id>.<region>.aws.cloud.qdrant.io:6334\n",
        ),
    }

    // DuckDB block: the path is always written; model_repo only when the chosen ort
    // model needs a non-default repo.
    y.push_str(
        "# DuckDB backend settings (only used when backend: duckdb). Ignored by Qdrant.\nduckdb:\n",
    );
    y.push_str("  # DuckDB database file. Created on first index; holds the table + HNSW index.\n");
    y.push_str(&format!("  path: {}\n", yaml_scalar(&a.duckdb_path)));
    y.push_str(
        "  # ort embedder: HuggingFace repo to download `onnx/model.onnx` + `tokenizer.json`\n\
         # from. Defaults to match the resolved `model`.\n",
    );
    if a.embedder == "ort" && a.model != DEFAULT_ORT_MODEL {
        y.push_str(&format!(
            "  model_repo: {}\n",
            yaml_scalar(&ort_model_repo_for(&a.model))
        ));
    } else {
        y.push_str("  # model_repo: jinaai/jina-embeddings-v2-base-code\n");
    }
    y.push_str(
        "  # Optional ONNX/HF model cache dir for offline reuse. When set, the model is\n\
         # downloaded/loaded from here instead of the default HF cache. (ort embedder only.)\n\
         # model_cache: .model_cache\n",
    );

    // Ollama block: url + model are written when ollama is the chosen embedder.
    y.push_str(
        "# Ollama embedder settings (only used when embedder: ollama). IMPORTANT: set\n\
         # `vector_dim` above to match the model — mxbai-embed-large = 1024, nomic-embed-text = 768.\n",
    );
    if a.embedder == "ollama" {
        y.push_str("ollama:\n");
        y.push_str(&format!("  url: {}\n", yaml_scalar(&a.ollama_url)));
        y.push_str(&format!("  model: {}\n", yaml_scalar(&a.model)));
    } else {
        y.push_str(
            "ollama:\n\
             # Ollama server URL. Default http://localhost:11434.\n\
             # url: http://localhost:11434\n\
             # Embedding model name (must be an embed-capable model you have pulled).\n\
             # model: mxbai-embed-large\n",
        );
    }

    // Walk filters: the standard prune list plus any extra dirs from the interview.
    y.push_str(
        "\n\
         # Directory names pruned entirely during the walk (fast — never descended into).\n\
         # NOTE: the original SKIP_DIRS (node_modules, .git, dist, build, target, .next,\n\
         # coverage, .turbo) are ALWAYS pruned in code regardless of this list — listing\n\
         # them here too is harmless and explicit. Add project-specific dirs below.\n\
         exclude_dirs:\n\
         \x20 - node_modules\n\
         \x20 - .git\n\
         \x20 - dist\n\
         \x20 - build\n\
         \x20 - target\n\
         \x20 - .next\n\
         \x20 - coverage\n\
         \x20 - .turbo\n\
         \x20 - __tests__ # every test directory\n",
    );
    for dir in &a.extra_exclude_dirs {
        y.push_str(&format!("  - {}\n", yaml_scalar(dir)));
    }

    y.push_str(
        "# Allow-list. When non-empty, ONLY files matching one of these globs are considered\n\
         # (exclude still applies on top). Empty/omitted = consider everything. Same glob syntax\n\
         # as `exclude`. Example: index only services + hooks:\n\
         #   include:\n\
         #     - \"src/services/**\"\n\
         #     - \"src/hooks/**\"\n\
         include: []\n\
         # Glob patterns matched against each file's path (relative to where you run).\n\
         # '**' spans directories; '*' stays within one path segment.\n\
         exclude:\n\
         \x20 # tests\n\
         \x20 - \"**/*.test.ts\"\n\
         \x20 - \"**/*.test.tsx\"\n\
         \x20 - \"**/*.spec.ts\"\n\
         \x20 - \"**/*.spec.tsx\"\n\
         \x20 # type declarations (no implementation logic)\n\
         \x20 - \"**/*.d.ts\"\n\
         \x20 # autogenerated — TypeScript\n\
         \x20 - \"**/*.gen.ts\"\n\
         \x20 - \"**/*.generated.ts\"\n\
         \x20 - \"**/generated/**\"\n\
         \x20 # autogenerated — Go\n\
         \x20 - \"**/*.pb.go\"\n\
         \x20 - \"**/*_gen.go\"\n\
         \x20 - \"**/*_generated.go\"\n\
         \x20 - \"**/mock_*.go\"\n\
         \x20 - \"**/zz_generated*.go\"\n",
    );

    y.push_str(
        "# Skip files whose first lines carry an autogenerated marker, regardless of name\n\
         # (e.g. Go's `// Code generated ... DO NOT EDIT.`, or `@generated`). Catches\n\
         # autogenerated files that don't follow a naming convention.\n\
         skip_generated_marker: true\n\
         # Strip comments (// and /* */) from C-family source before embedding/pushing, so\n\
         # only code reaches the index. String/template literals are preserved and line\n\
         # numbers stay accurate.\n\
         strip_comments: true\n\
         \n\
         # Honor opt-out marker comments (case-insensitive substring match on raw source):\n\
         #   sai-noindexing   — skip the chunk entirely from indexing (never embedded/stored)\n\
         #   sai-noduplicate  — include in search but exclude from duplicate clustering\n\
         # Works with any comment syntax (// # -- <!-- etc.). Granular to function (AST) or\n\
         # window (lines chunker). Both default to true.\n\
         # honor_noindex_marker: true\n\
         # honor_noduplicate_marker: true\n\
         \n\
         # Similarity-search thresholds for the `sai_find_similar` / `sai_find_duplicates` MCP tools AND\n\
         # the `similar` / `duplicates` CLI subcommands. Resolution per knob:\n\
         #   CLI flag / MCP tool arg  >  this config value  >  built-in default.\n\
         # These cutoffs are MODEL-SPECIFIC (a Qwen3 cosine of 0.85 is looser than e5's 0.85), so\n\
         # tune them for your embedder. Run `semanticastindexer similar --code \"...\" --min-score 0` to\n\
         # eyeball the raw score distribution, then set the cuts here. All fields optional.\n\
         # similarity:\n\
         #   find_similar_min_score: 0.85       # `similar`: drop neighbours below this cosine\n\
         #   duplicate_min_score: 0.93          # `duplicates`: edge cutoff between two chunks\n\
         #   duplicate_min_cluster_size: 2      # `duplicates`: smallest cluster to report\n\
         #   top_k: 10                          # `duplicates`: nearest-neighbour fan-out per chunk\n",
    );

    y
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;

    /// Parse rendered YAML back into the real `Config` — the round-trip every render
    /// must survive.
    fn parse(a: &Answers) -> Config {
        let yaml = render(a);
        serde_yaml_ng::from_str(&yaml)
            .unwrap_or_else(|e| panic!("generated config must parse: {e}\n---\n{yaml}"))
    }

    /// The pure-defaults render is the standard dummy: offline duckdb + ort + Jina,
    /// with the full filter lists and marker settings.
    #[test]
    fn default_render_round_trips_with_standard_values() {
        let cfg = parse(&Answers::default());
        assert_eq!(cfg.backend.as_deref(), Some("duckdb"));
        assert_eq!(cfg.embedder.as_deref(), Some("ort"));
        assert_eq!(cfg.collection.as_deref(), Some("source_code"));
        assert_eq!(
            cfg.model.as_deref(),
            Some("jinaai/jina-embeddings-v2-base-code")
        );
        assert_eq!(cfg.vector_dim, Some(768));
        assert!(
            cfg.chunker.is_none(),
            "chunker stays unset so the smart default applies"
        );
        assert_eq!(cfg.duckdb.path.as_deref(), Some(".index/code.duckdb"));
        assert!(
            cfg.duckdb.model_repo.is_none(),
            "default model needs no repo"
        );
        assert_eq!(cfg.qdrant.url, None);
        assert_eq!(cfg.ollama.url, None);
        assert!(cfg.exclude_dirs.contains(&"node_modules".to_string()));
        assert!(cfg.exclude_dirs.contains(&"__tests__".to_string()));
        assert!(cfg.include.is_empty());
        assert!(cfg.exclude.contains(&"**/*.test.ts".to_string()));
        assert!(cfg.exclude.contains(&"**/zz_generated*.go".to_string()));
        assert!(cfg.skip_generated_marker);
        assert_eq!(cfg.strip_comments, Some(true));
        assert!(cfg.honor_noindex_marker.is_none(), "left to default true");
        assert!(cfg.similarity.top_k.is_none(), "left to built-in defaults");
    }

    /// Qdrant answers land in the qdrant block; the URL is written only when given.
    #[test]
    fn qdrant_render_writes_url_when_given() {
        let a = Answers {
            backend: "qdrant".to_string(),
            model: "intfloat/multilingual-e5-small".to_string(),
            vector_dim: 384,
            qdrant_url: Some("https://c1.eu.cloud:6334".to_string()),
            ..Answers::default()
        };
        let cfg = parse(&a);
        assert_eq!(cfg.backend.as_deref(), Some("qdrant"));
        assert_eq!(cfg.vector_dim, Some(384));
        assert_eq!(cfg.qdrant.url.as_deref(), Some("https://c1.eu.cloud:6334"));

        let no_url = parse(&Answers {
            qdrant_url: None,
            ..a
        });
        assert_eq!(no_url.qdrant.url, None, "no URL → env var route");
    }

    /// Ollama answers fill the ollama block (url + model) for the embedder to read.
    #[test]
    fn ollama_render_writes_url_and_model() {
        let a = Answers {
            embedder: "ollama".to_string(),
            model: "nomic-embed-text".to_string(),
            vector_dim: 768,
            ollama_url: "http://gpu:11434".to_string(),
            ..Answers::default()
        };
        let cfg = parse(&a);
        assert_eq!(cfg.embedder.as_deref(), Some("ollama"));
        assert_eq!(cfg.ollama.url.as_deref(), Some("http://gpu:11434"));
        assert_eq!(cfg.ollama.model.as_deref(), Some("nomic-embed-text"));
    }

    /// A non-default ort model gets an explicit `duckdb.model_repo`; e5-small maps to
    /// its ONNX-export mirror.
    #[test]
    fn custom_ort_model_sets_model_repo() {
        let custom = parse(&Answers {
            model: "acme/strange-model".to_string(),
            vector_dim: 1024,
            ..Answers::default()
        });
        assert_eq!(
            custom.duckdb.model_repo.as_deref(),
            Some("acme/strange-model")
        );

        let e5 = parse(&Answers {
            model: "intfloat/multilingual-e5-small".to_string(),
            vector_dim: 384,
            ..Answers::default()
        });
        assert_eq!(
            e5.duckdb.model_repo.as_deref(),
            Some("Xenova/multilingual-e5-small"),
            "e5-small's ONNX export lives in the Xenova mirror"
        );
    }

    /// Extra exclude dirs from the interview are appended to the standard prune list.
    #[test]
    fn extra_exclude_dirs_are_appended() {
        let cfg = parse(&Answers {
            extra_exclude_dirs: vec!["vendor".to_string(), "examples".to_string()],
            ..Answers::default()
        });
        for dir in ["node_modules", "vendor", "examples"] {
            assert!(
                cfg.exclude_dirs.contains(&dir.to_string()),
                "missing {dir} in {:?}",
                cfg.exclude_dirs
            );
        }
    }

    /// Pathological free-text answers (spaces, `: `, `#`, quotes) are YAML-quoted so
    /// they round-trip to exactly what was typed instead of breaking the file.
    #[test]
    fn pathological_values_are_quoted_and_round_trip() {
        let a = Answers {
            collection: "my project: v2".to_string(),
            model: "acme/model with \"space\"".to_string(),
            vector_dim: 512,
            duckdb_path: "dir with space/code.duckdb".to_string(),
            extra_exclude_dirs: vec!["weird #dir".to_string()],
            ..Answers::default()
        };
        let cfg = parse(&a);
        assert_eq!(cfg.collection.as_deref(), Some("my project: v2"));
        assert_eq!(cfg.model.as_deref(), Some("acme/model with \"space\""));
        assert_eq!(
            cfg.duckdb.path.as_deref(),
            Some("dir with space/code.duckdb")
        );
        assert!(cfg.exclude_dirs.contains(&"weird #dir".to_string()));
    }

    /// Values YAML would type-coerce (numbers, booleans) survive as strings.
    #[test]
    fn numeric_and_boolean_looking_values_stay_strings() {
        for name in ["123", "true", "no"] {
            let cfg = parse(&Answers {
                collection: name.to_string(),
                ..Answers::default()
            });
            assert_eq!(cfg.collection.as_deref(), Some(name), "for {name}");
        }
    }

    /// Ordinary identifiers, paths, and URLs stay unquoted — the default render is
    /// byte-stable against the introduction of quoting.
    #[test]
    fn plain_values_stay_unquoted() {
        let yaml = render(&Answers::default());
        assert!(yaml.contains("collection: source_code\n"));
        assert!(yaml.contains("model: jinaai/jina-embeddings-v2-base-code\n"));
        assert!(yaml.contains("  path: .index/code.duckdb\n"));
    }
}
