//! Walk / filter / chunk / strip logic that turns a `Plan` into `Vec<CodeChunk>`
//! work items.
//!
//! This module is the single source of truth for "what files and ranges get embedded".
//! The pure chunking paths (`collect_chunks`, `build_chunks`, `dry_run`) never touch
//! a vector backend. The small bridge function `reindex_file` (used by both CLI `sync`
//! and the MCP `refresh` tool) does call into a `Backend` to apply deletes + upserts for
//! one file; that is the only place in the module that interacts with storage.

use std::collections::HashMap;
use std::hash::{Hash, Hasher};
use std::path::Path;
use twox_hash::XxHash64;
use walkdir::WalkDir;

use crate::config::Plan;
use crate::vectordbs::{Backend, CodeChunk};
use anyhow::Result;

/// Extensions whose comments are stripped (C-family `//` and `/* */`). Covers TS now, Go later.
const CSTYLE_EXTS: &[&str] = &[
    "ts", "tsx", "js", "jsx", "mjs", "cjs", "go", "rs", "java", "c", "h", "cc", "cpp", "hpp", "cs",
    "kt", "swift", "scala",
];
/// Secondary line guard for the line-window chunker. The primary size bound is
/// `plan.max_chunk_chars` (model-aware); this caps the line count of a single window.
const MAX_LINES: usize = 60;
const OVERLAP_LINES: usize = 8;
/// First N bytes scanned for an autogenerated marker.
const MARKER_SCAN_BYTES: usize = 600;
/// Case-insensitive substrings that mark an autogenerated file.
const GENERATED_MARKERS: &[&str] = &[
    "do not edit",
    "@generated",
    "code generated",
    "auto-generated",
    "autogenerated",
    "this file is generated",
];

/// One embeddable slice of a source file.
struct Chunk {
    start_line: usize,
    end_line: usize,
    text: String,
    /// Captured symbol name (AST chunker only). `None` for line-window chunks.
    symbol: Option<String>,
}

/// Read → strip comments → chunk → build code chunks for one file (no generated-marker check here).
///
/// Comments are stripped BEFORE chunking (so only code is embedded). The AST chunker
/// therefore parses the comment-stripped text — acceptable, since stripping preserves
/// line count and code structure.
pub fn build_chunks(plan: &Plan, path: &Path, rel: &str, raw: &str) -> Vec<CodeChunk> {
    let content = if plan.strip_comments && is_cstyle(path) {
        strip_c_comments(raw)
    } else {
        raw.to_string()
    };
    let language = language_for_path(path);
    // Marker detection scans the RAW (pre-strip) lines, since comments are stripped
    // before chunking but strip_c_comments preserves the line count, so a chunk's line
    // range still indexes the original raw lines.
    let raw_lines: Vec<&str> = raw.lines().collect();
    chunk_content(plan, path, &content)
        .into_iter()
        .filter_map(|c| {
            let (noindex, nodup) = scan_markers(
                &raw_lines,
                c.start_line,
                c.end_line,
                plan.honor_noindex_marker,
                plan.honor_noduplicate_marker,
            );
            if noindex {
                return None;
            }
            Some(CodeChunk {
                id: point_id(rel, c.start_line),
                path: rel.to_string(),
                language: language.clone(),
                start_line: c.start_line,
                end_line: c.end_line,
                text: c.text,
                symbol: c.symbol,
                commit_sha: None,
                dirty: false,
                no_duplicate: nodup,
            })
        })
        .collect()
}

/// Scan the RAW (pre-comment-strip) line span of a chunk for opt-out markers.
/// Returns (noindex, noduplicate). Case-insensitive substring match — language-agnostic.
fn scan_markers(
    raw_lines: &[&str],
    start_line: usize,
    end_line: usize,
    noindex_on: bool,
    nodup_on: bool,
) -> (bool, bool) {
    if !noindex_on && !nodup_on {
        return (false, false);
    }
    let s = start_line.saturating_sub(1);
    let e = end_line.min(raw_lines.len());
    if s >= e {
        return (false, false);
    }
    let mut noindex = false;
    let mut nodup = false;
    for line in &raw_lines[s..e] {
        let lower = line.to_ascii_lowercase();
        if noindex_on && lower.contains("sai-noindexing") {
            noindex = true;
        }
        if nodup_on && lower.contains("sai-noduplicate") {
            nodup = true;
        }
    }
    (noindex, nodup)
}

/// Dispatch to the configured chunker. `lines` (default) is the line-window chunker;
/// `ast` is the tree-sitter chunker (feature-gated). `ast` falls back to the line
/// chunker for any file it cannot parse (non-TS ext, or a parse error).
fn chunk_content(plan: &Plan, path: &Path, content: &str) -> Vec<Chunk> {
    match plan.chunker.as_str() {
        "lines" => chunk_lines(content, plan.max_chunk_chars),
        "ast" => chunk_ast(path, content, plan.max_chunk_chars),
        // build_plan does not validate the value, so guard here. Unknown → line chunker.
        _ => chunk_lines(content, plan.max_chunk_chars),
    }
}

/// AST chunker entry point. When the `ast` feature is compiled in, we try to use a
/// language-specific tree-sitter grammar (TS/TSX + Rust + Go + Python) to emit symbol-aware
/// chunks. For unsupported extensions or parse failures, we fall back to the line
/// chunker. When the feature is NOT compiled in, selecting `chunker: ast` is a hard
/// error (mirrors the other feature gates).
#[cfg(feature = "ast")]
fn chunk_ast(path: &Path, content: &str, cap: usize) -> Vec<Chunk> {
    ast::try_chunk_ast(path, content, cap).unwrap_or_else(|| chunk_lines(content, cap))
}

#[cfg(not(feature = "ast"))]
fn chunk_ast(_path: &Path, _content: &str, _cap: usize) -> Vec<Chunk> {
    // The plan validates this earlier (see `ensure_chunker_available`), so this is
    // unreachable in practice; keep it total for safety.
    Vec::new()
}

/// Reject `chunker: ast` when the `ast` feature was not compiled in — a clear,
/// actionable error that mirrors the backend/embedder feature gating. Call once at
/// startup before any indexing.
pub fn ensure_chunker_available(plan: &Plan) -> anyhow::Result<()> {
    match plan.chunker.as_str() {
        "lines" => Ok(()),
        "ast" => {
            #[cfg(feature = "ast")]
            {
                Ok(())
            }
            #[cfg(not(feature = "ast"))]
            {
                anyhow::bail!(
                    "chunker 'ast' selected but this binary was built without the 'ast' feature (rebuild with --features ast)"
                )
            }
        }
        other => anyhow::bail!("unknown chunker '{other}' (expected 'lines' or 'ast')"),
    }
}

/// Walk the root and produce all `CodeChunk` work items for the plan, plus the
/// count of files skipped by config. Pure (no backend calls).
pub fn collect_chunks(plan: &Plan) -> (Vec<CodeChunk>, usize, usize) {
    let mut chunks: Vec<CodeChunk> = Vec::new();
    let mut files = 0usize;
    let mut skipped = 0usize;

    for entry in WalkDir::new(&plan.root)
        .into_iter()
        .filter_entry(|e| !is_pruned_dir(e.path(), plan))
        .filter_map(std::result::Result::ok)
    {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        let rel = path.to_string_lossy().to_string();
        let key = rel.trim_start_matches("./");

        let Some(raw) = load_file_for_indexing(plan, path, key, Some(&mut skipped)) else {
            continue;
        };

        let file_chunks = build_chunks(plan, path, key, &raw);
        if file_chunks.is_empty() {
            continue;
        }
        files += 1;
        chunks.extend(file_chunks);
    }

    (chunks, files, skipped)
}

/// Walk + report inclusions/exclusions without touching any backend.
///
/// LOGICAL INVARIANT: The inclusion/exclusion decisions made here must be
/// semantically identical to what `collect_chunks` will do for the same Plan.
/// We deliberately call `passes_globs` (the single source of truth) for the
/// actual pass/fail decision, and only use the separate checks to produce
/// human-friendly exclusion *reasons* for the report. This prevents drift.
pub fn dry_run(plan: &Plan) {
    let mut included: Vec<String> = Vec::new();
    let mut excluded: Vec<(String, &'static str)> = Vec::new();

    for entry in WalkDir::new(&plan.root)
        .into_iter()
        .filter_entry(|e| !is_pruned_dir(e.path(), plan))
        .filter_map(std::result::Result::ok)
    {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if !has_wanted_ext(path, &plan.ext) {
            continue;
        }
        let rel = path.to_string_lossy().to_string();
        let key = rel.trim_start_matches("./");

        // Use the shared decision function for the actual include/exclude gate.
        // The manual checks below are only to produce a useful "why" for the report.
        if !plan.passes_globs(key) {
            if plan.include_active && !plan.include.is_match(key) {
                excluded.push((rel, "not-included"));
            } else {
                excluded.push((rel, "glob"));
            }
            continue;
        }

        // Shared filtering for generated-marker (and read). We pass None for the
        // skipped counter because dry_run classifies reasons itself.
        if load_file_for_indexing(plan, path, key, None).is_none() {
            // The only remaining reason load_file_for_indexing can return None here
            // (after we already passed the glob check) is the generated marker.
            excluded.push((rel, "generated-marker"));
            continue;
        }

        // Note: We do *not* simulate build_chunks here. Files that become empty
        // after stripping will be included in the "would index" count but will
        // produce zero chunks at runtime (same as collect_chunks behavior).
        included.push(rel);
    }

    println!("DRY RUN — root '{}', ext {}", plan.root, plan.ext.join("/"));
    println!("collection '{}', model '{}'", plan.collection, plan.model);
    println!(
        "strip_comments: {}   skip_generated_marker: {}",
        plan.strip_comments, plan.skip_generated
    );
    let mut pruned: Vec<&str> = plan.exclude_dirs.iter().map(String::as_str).collect();
    pruned.sort_unstable();
    println!("pruned dirs: {}", pruned.join(", "));
    println!(
        "\nWOULD INDEX: {} file(s)   EXCLUDED: {} file(s)",
        included.len(),
        excluded.len()
    );

    let mut by_reason: HashMap<&str, usize> = HashMap::new();
    for (_, reason) in &excluded {
        *by_reason.entry(reason).or_default() += 1;
    }
    for (reason, n) in &by_reason {
        println!("  excluded by {reason}: {n}");
    }

    println!("\nsample excluded:");
    for (rel, reason) in excluded.iter().take(15) {
        println!("  - {rel}  [{reason}]");
    }
    println!("\nsample included:");
    for rel in included.iter().take(15) {
        println!("  + {rel}");
    }
}

/// Deterministic u64 id from path + chunk start, so re-runs update points in place.
///
/// Uses `XxHash64` with a fixed seed (0) so IDs are STABLE across builds and
/// machines (unlike `DefaultHasher`, whose algorithm is unspecified). This is
/// shared by every backend so Qdrant and DuckDB key the same chunk identically.
///
/// NOTE: switching off `DefaultHasher` changes existing Qdrant point IDs — a
/// one-time `flush` / `--recreate` is needed after this change.
pub fn point_id(path: &str, start_line: usize) -> u64 {
    let mut hasher = XxHash64::with_seed(0);
    path.hash(&mut hasher);
    start_line.hash(&mut hasher);
    hasher.finish()
}

/// Split whole-file content into line windows bounded by MAX_LINES / `cap` chars with
/// small overlap. The classic chunker (`chunker: lines`); all chunks have `symbol: None`.
fn chunk_lines(content: &str, cap: usize) -> Vec<Chunk> {
    let lines: Vec<&str> = content.lines().collect();
    chunk_line_range(&lines, 0, lines.len(), cap)
}

/// Line-window chunker over a sub-range `[from, to)` of `lines` (0-based), emitting
/// 1-based `start_line`/`end_line` that account for the range offset. Shared by the
/// whole-file [`chunk_lines`] and the AST chunker's oversize/remainder line-splitting,
/// so window sizing and overlap can never drift between the two paths.
fn chunk_line_range(lines: &[&str], from: usize, to: usize, cap: usize) -> Vec<Chunk> {
    let mut chunks = Vec::new();
    let mut i = from;
    while i < to {
        let mut j = i;
        let mut chars = 0usize;
        while j < to && (j - i) < MAX_LINES && chars < cap {
            chars += lines[j].len() + 1;
            j += 1;
        }
        let text = lines[i..j].join("\n");
        if !text.trim().is_empty() {
            chunks.push(Chunk {
                start_line: i + 1,
                end_line: j,
                text,
                symbol: None,
            });
        }
        if j >= to {
            break;
        }
        i = if j > i + OVERLAP_LINES {
            j - OVERLAP_LINES
        } else {
            j
        };
    }
    chunks
}

fn is_cstyle(path: &Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| CSTYLE_EXTS.contains(&e))
}

/// Remove C-family comments (`//` line, `/* */` block) while preserving string and
/// template literals AND the exact newline count (so payload line numbers stay accurate).
///
/// LOGICAL INVARIANT: After stripping, the number of lines must be identical to the
/// input, and every surviving line of code must have the same 1-based line number it
/// had in the original source. This is critical so that `start_line`/`end_line` in
/// the vector payload always point at the real file.
///
/// Known limitation: regex literals are not tracked, so a `//` *inside* a regex literal
/// would be treated as a line comment. This is vanishingly rare in real code.
fn strip_c_comments(src: &str) -> String {
    #[derive(PartialEq)]
    enum State {
        Normal,
        Line,
        Block,
        Dq,  // "double"
        Sq,  // 'single'
        Tpl, // `template`
    }
    let chars: Vec<char> = src.chars().collect();
    let n = chars.len();
    let mut out = String::with_capacity(src.len());
    let mut state = State::Normal;
    let mut i = 0;
    while i < n {
        let c = chars[i];
        let next = if i + 1 < n { chars[i + 1] } else { '\0' };
        match state {
            State::Normal => match (c, next) {
                ('/', '/') => {
                    state = State::Line;
                    i += 2;
                }
                ('/', '*') => {
                    state = State::Block;
                    i += 2;
                }
                ('"', _) => {
                    out.push(c);
                    state = State::Dq;
                    i += 1;
                }
                ('\'', _) => {
                    out.push(c);
                    state = State::Sq;
                    i += 1;
                }
                ('`', _) => {
                    out.push(c);
                    state = State::Tpl;
                    i += 1;
                }
                _ => {
                    out.push(c);
                    i += 1;
                }
            },
            State::Line => {
                // Drop everything up to (not including) the newline.
                if c == '\n' {
                    out.push('\n');
                    state = State::Normal;
                }
                i += 1;
            }
            State::Block => {
                if c == '*' && next == '/' {
                    state = State::Normal;
                    i += 2;
                } else {
                    if c == '\n' {
                        out.push('\n'); // keep line count stable
                    }
                    i += 1;
                }
            }
            State::Dq | State::Sq | State::Tpl => {
                out.push(c);
                if c == '\\' && i + 1 < n {
                    out.push(chars[i + 1]); // copy escaped char verbatim
                    i += 2;
                    continue;
                }
                let closes = match state {
                    State::Dq => c == '"',
                    State::Sq => c == '\'',
                    State::Tpl => c == '`',
                    _ => false,
                };
                if closes {
                    state = State::Normal;
                }
                i += 1;
            }
        }
    }
    out
}

/// True if the file's opening bytes carry an autogenerated marker.
pub fn is_generated(content: &str) -> bool {
    // Cap the scan at MARKER_SCAN_BYTES, but back up to the nearest char
    // boundary so we never slice inside a multi-byte UTF-8 char (e.g. '─').
    let limit = content.len().min(MARKER_SCAN_BYTES);
    let end = (0..=limit)
        .rev()
        .find(|&i| content.is_char_boundary(i))
        .unwrap_or(0);
    let head = content[..end].to_lowercase();
    GENERATED_MARKERS.iter().any(|m| head.contains(m))
}

fn is_pruned_dir(path: &Path, plan: &Plan) -> bool {
    path.file_name()
        .and_then(|n| n.to_str())
        .is_some_and(|n| plan.exclude_dirs.contains(n))
}

pub fn has_wanted_ext(path: &Path, wanted: &[String]) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| wanted.iter().any(|w| w == e))
}

/// The `language` payload label for a file, derived from its extension (lowercased):
/// `foo.ts` → "ts", `Bar.TSX` → "tsx". Files reaching here always passed
/// `has_wanted_ext`, so an extension is expected; a missing one falls back to "".
pub(crate) fn language_for_path(path: &Path) -> String {
    path.extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_ascii_lowercase())
        .unwrap_or_default()
}

/// Load and filter a file for indexing.
///
/// Returns `Some(raw_content)` only if the file passes:
/// - wanted extension
/// - glob filters (`include`/`exclude` via `passes_globs`)
/// - not an autogenerated file (when `plan.skip_generated`)
///
/// On skip conditions that `collect_chunks` counts as "skipped by config",
/// the optional `skipped` counter is incremented.
///
/// This is the **single source of truth** for the decision "should we attempt
/// to produce chunks from this file?". Used by `collect_chunks`, `dry_run`,
/// and `reindex_file` (and therefore both CLI sync and MCP refresh).
///
/// Binary / non-UTF8 files are silently ignored (not counted in `skipped`).
pub(crate) fn load_file_for_indexing(
    plan: &Plan,
    path: &Path,
    key: &str,
    skipped: Option<&mut usize>,
) -> Option<String> {
    if !has_wanted_ext(path, &plan.ext) {
        return None;
    }
    if !plan.passes_globs(key) {
        if let Some(c) = skipped {
            *c += 1;
        }
        return None;
    }
    let raw = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return None, // binary / non-utf8 — do not count toward skipped
    };
    if plan.skip_generated && is_generated(&raw) {
        if let Some(c) = skipped {
            *c += 1;
        }
        return None;
    }
    Some(raw)
}

/// AST chunker (tree-sitter, TypeScript/TSX + Rust + Go + Python). Pure logic, like the rest of this module.
///
/// This index exists to compare FUNCTIONS for near-duplicates, so the AST chunker emits
/// function chunks ONLY — never classes, interfaces, type aliases, consts, mods, or other
/// top-level statements (those would flood the index with tiny, near-identical non-function
/// vectors and make every `duplicates` run report the whole codebase).
///
/// Strategy:
/// - Parse the file with the matching grammar. A root parse error → `None` so the caller
///   falls back to the line chunker. Only `.ts`/`.tsx`/`.rs`/`.go`/`.py` are AST-handled; any
///   other extension returns `None`.
/// - A tree-sitter [`Query`] captures NAMED function-like nodes at ANY depth: function
///   declarations, methods, and arrow/function-expression bindings. The binding name is the
///   chunk symbol. Bare anonymous closures are NOT captured (tiny near-identical lambdas
///   would otherwise collapse every `duplicates` run into one cluster).
/// - Each captured function → ONE chunk (symbol + node line range); oversized functions are
///   line-split over their own span via the shared line chunker, keeping the symbol.
/// - Captures sharing an exact span are deduped (prefer the symboled one). Non-function code
///   is intentionally dropped — a file with no functions produces no chunks.
#[cfg(feature = "ast")]
mod ast {
    use super::{Chunk, chunk_line_range};
    use std::collections::HashMap;
    use std::path::Path;
    use tree_sitter::{Node, Parser, Query, QueryCursor, StreamingIterator};

    // --- TypeScript / TSX query ---
    /// The index compares FUNCTIONS to find near-duplicates, so we capture only NAMED
    /// function-like nodes — never classes/interfaces/type-aliases or top-level statements.
    /// Coverage: named function declarations, methods, and arrow/function-expression `const`s
    /// (the binding name becomes the symbol). Bare anonymous closures are intentionally NOT
    /// captured: one-line lambdas like `|x| x.foo()` are tiny and near-identical, which
    /// collapses every `duplicates` run into one giant cluster.
    const TS_QUERY_SRC: &str = r#"
(function_declaration name: (identifier) @name) @item
(method_definition name: (property_identifier) @name) @item
(lexical_declaration
  (variable_declarator
    name: (identifier) @name
    value: [(arrow_function) (function_expression)] @item))
"#;

    // --- Rust query ---
    /// Functions only (see the TS note): every `function_item` — free functions, `impl`
    /// methods, trait default-body methods, and nested functions, since a `function_item`
    /// pattern matches at any depth. Non-function items (struct/enum/trait/impl/mod/const/
    /// static/type) and bare closures are intentionally NOT captured.
    const RUST_QUERY_SRC: &str = r#"
(function_item name: (identifier) @name) @item
"#;

    // --- Go query ---
    /// Functions only (see the TS/Rust notes): top-level `func` declarations and methods
    /// (`func (r T) M()`). Go's only nested-function form is a func literal (closure); like
    /// Rust closures, those are intentionally NOT captured. Method symbols are the bare
    /// method name (the receiver is not qualified in).
    const GO_QUERY_SRC: &str = r#"
(function_declaration name: (identifier) @name) @item
(method_declaration name: (field_identifier) @name) @item
"#;

    // --- Python query ---
    /// Functions only (see the TS note): every `function_definition` — free functions,
    /// class methods, nested functions, and `async def`s are all the same node kind in
    /// tree-sitter-python, and the pattern matches at any depth. Decorators live in a
    /// wrapping `decorated_definition`, so the chunk span starts at `def` (decorator
    /// lines are not embedded). Anonymous `lambda`s are intentionally NOT captured.
    const PY_QUERY_SRC: &str = r#"
(function_definition name: (identifier) @name) @item
"#;

    /// One captured function node: byte span, line span (1-based), and symbol (the
    /// function's name; `None` for anonymous closures).
    struct Item {
        symbol: Option<String>,
        start_byte: usize,
        end_byte: usize,
        start_line: usize, // 1-based
        end_line: usize,   // 1-based, inclusive
    }

    impl Item {
        /// Build an `Item` from a captured node and its (optional) symbol.
        fn from_node(n: Node, symbol: Option<String>) -> Self {
            Item {
                symbol,
                start_byte: n.start_byte(),
                end_byte: n.end_byte(),
                start_line: n.start_position().row + 1,
                end_line: n.end_position().row + 1,
            }
        }
    }

    /// Try to produce AST-based chunks. Dispatches to language-specific implementations.
    /// Returns `None` to fall back to the line chunker.
    pub fn try_chunk_ast(path: &Path, content: &str, cap: usize) -> Option<Vec<Chunk>> {
        let ext = path.extension().and_then(|e| e.to_str())?;

        // Select the (grammar, query) pair by extension, then run the single shared
        // collection path. Each language is just a grammar + query into that path.
        let (language, query_src): (tree_sitter::Language, &str) = match ext {
            "rs" => (tree_sitter_rust::LANGUAGE.into(), RUST_QUERY_SRC),
            "go" => (tree_sitter_go::LANGUAGE.into(), GO_QUERY_SRC),
            "py" => (tree_sitter_python::LANGUAGE.into(), PY_QUERY_SRC),
            "ts" => (
                tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(),
                TS_QUERY_SRC,
            ),
            "tsx" => (tree_sitter_typescript::LANGUAGE_TSX.into(), TS_QUERY_SRC),
            _ => return None,
        };
        collect_function_chunks(language, query_src, content, cap)
    }

    /// Parse `content` with `language`, run `query_src` (which MUST define `@name` + `@item`
    /// captures), collect each captured function node, and hand off to the shared builder.
    /// A root parse error returns `None` so the caller falls back to the line chunker. This
    /// is the single per-language collection path shared by TS, Rust, Go, and Python.
    fn collect_function_chunks(
        language: tree_sitter::Language,
        query_src: &str,
        content: &str,
        cap: usize,
    ) -> Option<Vec<Chunk>> {
        let mut parser = Parser::new();
        parser.set_language(&language).ok()?;
        let tree = parser.parse(content, None)?;
        let root = tree.root_node();
        // A root-level error means the parse is unreliable → fall back.
        if root.is_error() || root.kind() == "ERROR" {
            return None;
        }

        let query = Query::new(&language, query_src).ok()?;
        let name_idx = query.capture_index_for_name("name")?;
        let item_idx = query.capture_index_for_name("item")?;

        let src = content.as_bytes();
        let mut items: Vec<Item> = Vec::new();
        let mut cursor = QueryCursor::new();
        let mut matches = cursor.matches(&query, root, src);
        while let Some(m) = matches.next() {
            let mut node: Option<Node> = None;
            let mut symbol: Option<String> = None;
            for cap in m.captures {
                if cap.index == item_idx {
                    node = Some(cap.node);
                } else if cap.index == name_idx {
                    symbol = cap.node.utf8_text(src).ok().map(str::to_string);
                }
            }
            if let Some(n) = node {
                items.push(Item::from_node(n, symbol));
            }
        }

        build_chunks_from_items(items, content, cap)
    }

    /// Extract the text of a node by its 1-based inclusive line range.
    fn node_text(lines: &[&str], start_line: usize, end_line: usize) -> String {
        let s = start_line.saturating_sub(1);
        let e = end_line.min(lines.len());
        if s >= e {
            return String::new();
        }
        lines[s..e].join("\n")
    }

    /// Line-split an oversized node's own span via the shared line chunker, tagging each
    /// resulting window with the node's symbol so the symbol survives the split.
    fn line_split_node(
        lines: &[&str],
        it: &Item,
        cap: usize,
        symbol: Option<String>,
    ) -> Vec<Chunk> {
        let from = it.start_line.saturating_sub(1);
        let to = it.end_line.min(lines.len());
        chunk_line_range(lines, from, to, cap)
            .into_iter()
            .map(|mut c| {
                c.symbol = symbol.clone();
                c
            })
            .collect()
    }

    /// Turn captured function nodes into chunks. Shared by all the per-language collectors.
    ///
    /// Each function becomes ONE chunk (or several windows if it exceeds `cap`). Any two
    /// captures that share an EXACT span are deduped to a single chunk, preferring the one
    /// that carries a symbol (defensive — patterns generally don't overlap now). Nested
    /// functions are emitted in their own right AND remain part of their enclosing function's
    /// chunk (no carve-out); overlap is acceptable for near-duplicate detection. Non-function
    /// code is never chunked.
    fn build_chunks_from_items(items: Vec<Item>, content: &str, cap: usize) -> Option<Vec<Chunk>> {
        let lines: Vec<&str> = content.lines().collect();

        // Dedupe by exact byte span; prefer the symboled capture.
        let mut by_span: HashMap<(usize, usize), Item> = HashMap::new();
        for it in items {
            let key = (it.start_byte, it.end_byte);
            let replace = match by_span.get(&key) {
                Some(existing) => existing.symbol.is_none() && it.symbol.is_some(),
                None => true,
            };
            if replace {
                by_span.insert(key, it);
            }
        }
        let mut deduped: Vec<Item> = by_span.into_values().collect();
        deduped.sort_by_key(|it| (it.start_byte, it.end_byte));

        let mut chunks: Vec<Chunk> = Vec::new();
        for it in &deduped {
            let len = it.end_byte.saturating_sub(it.start_byte);
            if len <= cap {
                let text = node_text(&lines, it.start_line, it.end_line);
                if !text.trim().is_empty() {
                    chunks.push(Chunk {
                        start_line: it.start_line,
                        end_line: it.end_line,
                        text,
                        symbol: it.symbol.clone(),
                    });
                }
            } else {
                chunks.extend(line_split_node(&lines, it, cap, it.symbol.clone()));
            }
        }

        chunks.sort_by_key(|c| c.start_line);
        Some(chunks)
    }
}

/// Outcome of re-indexing a single path: either it was removed (gone/excluded/empty,
/// with a reason) or re-indexed with N fresh chunks.
///
/// This type is intentionally small and owned so it can be returned across the
/// worker-thread boundary in the MCP server.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReindexOutcome {
    /// File removed from the index. `reason` explains why (for logging only).
    Removed { reason: &'static str },
    /// File re-indexed with `chunks` fresh chunks upserted.
    Reindexed { chunks: usize },
}

/// Shared per-file re-index step used by BOTH `sync` (CLI) and the MCP `refresh` tool.
///
/// Always deletes the file's existing points first, then — if the path currently on disk
/// is still indexable (exists + wanted ext + passes globs + not generated + produces chunks)
/// — chunks it (honoring `plan.chunker`), embeds, and upserts.
///
/// The caller is responsible for wrapping the overall operation in `begin_bulk()` / `end_bulk()`
/// (required for DuckDB HNSW correctness).
///
/// This lives in the indexer module (rather than main) because the decision logic
/// ("should this rel produce chunks right now?") must stay in sync with `collect_chunks`
/// and `dry_run`.
pub async fn reindex_file(
    backend: &Backend,
    plan: &Plan,
    rel: &str,
    ctx: &crate::git::GitContext,
) -> Result<ReindexOutcome> {
    let key = rel.trim_start_matches("./");
    // Always remove the file's existing points first ("remove completely").
    backend.delete_by_path(key).await?;

    let path = Path::new(rel);
    if !path.is_file() {
        return Ok(ReindexOutcome::Removed { reason: "removed" });
    }

    // Single source of truth for ext + globs + generated marker.
    match load_file_for_indexing(plan, path, key, None) {
        Some(raw) => {
            let mut file_chunks = build_chunks(plan, path, key, &raw);
            if file_chunks.is_empty() {
                return Ok(ReindexOutcome::Removed {
                    reason: "removed: no indexable content",
                });
            }
            for c in &mut file_chunks {
                c.commit_sha = ctx.sha.clone();
                c.dirty = ctx.dirty;
            }
            let n = file_chunks.len();
            backend.upsert(&file_chunks).await?;
            Ok(ReindexOutcome::Reindexed { chunks: n })
        }
        None => {
            if plan.skip_generated
                && let Ok(raw) = std::fs::read_to_string(path)
                && is_generated(&raw)
            {
                return Ok(ReindexOutcome::Removed {
                    reason: "removed: autogenerated",
                });
            }
            Ok(ReindexOutcome::Removed { reason: "removed" })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_line_and_block_keeps_strings_and_linecount() {
        let src = "// gone\n\
                   const url = \"http://example.com\" // trailing\n\
                   /* block\n   spanning */\n\
                   const tpl = `keep ${a} and // not a comment`\n\
                   const s = \"a // b in string\"\n\
                   fn() // end\n";
        let out = strip_c_comments(src);
        // line count preserved (payload line numbers stay valid)
        assert_eq!(src.lines().count(), out.lines().count());
        // url inside a string keeps its `//`
        assert!(out.contains("\"http://example.com\""));
        // `//` inside a normal string is not treated as a comment
        assert!(out.contains("\"a // b in string\""));
        // template literal content (incl. its `//`) is preserved verbatim
        assert!(out.contains("`keep ${a} and // not a comment`"));
        // actual comments are gone
        assert!(!out.contains("gone"));
        assert!(!out.contains("trailing"));
        assert!(!out.contains("spanning"));
        assert!(!out.contains("end"));
        // code survives
        assert!(out.contains("const url ="));
        assert!(out.contains("fn()"));
    }

    #[test]
    fn point_id_is_stable_and_deterministic() {
        // Same inputs ⇒ same id (so re-runs update points in place).
        assert_eq!(point_id("src/foo.ts", 1), point_id("src/foo.ts", 1));
        // Different path or line ⇒ different id.
        assert_ne!(point_id("src/foo.ts", 1), point_id("src/bar.ts", 1));
        assert_ne!(point_id("src/foo.ts", 1), point_id("src/foo.ts", 2));
        // Pinned value: XxHash64(seed=0) over path+start_line must not drift across
        // builds/machines. If this fails, the ID algorithm changed (re-index needed).
        assert_eq!(point_id("src/foo.ts", 1), 10293058119199652890_u64);
    }

    #[test]
    fn handles_escaped_quotes() {
        let src = "const s = \"he said \\\"hi\\\" // x\" // real comment\n";
        let out = strip_c_comments(src);
        assert!(out.contains("\"he said \\\"hi\\\" // x\""));
        assert!(!out.contains("real comment"));
    }

    /// Documents the known limitation of the comment stripper: regex literals are not
    /// tracked. A `//` or `/*` inside a regex literal will be (incorrectly) treated as
    /// the start of a comment. This is explicitly accepted and documented because it is
    /// extremely rare in real code and would require a full JS/TS lexer to handle
    /// correctly.
    #[test]
    fn stripper_known_limitation_regex_literals() {
        // The `//` inside the regex will be treated as a line comment start.
        let src = "const re = /http:\\/\\//; // real comment\n";
        let out = strip_c_comments(src);

        // Current (accepted) behavior: everything after the first // in the regex is dropped.
        assert!(!out.contains("real comment"));
        // The regex itself is mangled (this is the known limitation).
        assert!(out.contains("const re = /http:"));
    }

    #[test]
    fn is_generated_handles_multibyte_at_scan_boundary() {
        // Regression: the scan cap (MARKER_SCAN_BYTES) once sliced by raw byte
        // index and panicked when the cutoff landed inside a multi-byte char.
        // Pad with a box-drawing char ('─', 3 bytes) so the cap lands mid-char.
        let content = "─".repeat(MARKER_SCAN_BYTES);
        // Must not panic, and these box chars carry no generated marker.
        assert!(!is_generated(&content));

        // Marker within scan range is still detected even with multibyte padding.
        let with_marker = format!("// @generated\n{}", "─".repeat(MARKER_SCAN_BYTES));
        assert!(is_generated(&with_marker));
    }

    /// The line chunker honors the char cap: a tiny cap forces many small windows;
    /// every emitted window is within the cap's chars (modulo the always-include-one-line
    /// rule for a single oversized line).
    #[test]
    fn line_chunker_respects_char_cap() {
        // 20 short lines of ~5 chars each.
        let content = (0..20)
            .map(|i| format!("ln{i:02}"))
            .collect::<Vec<_>>()
            .join("\n");
        let big = chunk_lines(&content, 1400);
        let small = chunk_lines(&content, 12); // ~2 lines per window
        assert_eq!(
            big.len(),
            1,
            "1400-char cap fits the whole file in one chunk"
        );
        assert!(
            small.len() > big.len(),
            "a 12-char cap must produce more, smaller windows ({} vs {})",
            small.len(),
            big.len()
        );
        // Each small window (beyond its first line) stays at/under the cap.
        for c in &small {
            let lines = c.text.lines().count();
            assert!(lines <= MAX_LINES);
            assert!(c.symbol.is_none(), "line chunks have no symbol");
        }
    }

    /// AST chunker over a representative TS fixture: functions + a class with methods +
    /// a top-level import and consts. The index is function-only, so it asserts: every
    /// function/method is captured by name, and NON-function code (import, class shell,
    /// top-level consts) is NOT emitted as any chunk.
    #[cfg(feature = "ast")]
    #[test]
    fn ast_captures_only_functions_and_methods() {
        use std::path::Path;

        let src = "\
import { helper } from \"./helper\"

export function alpha(): number {
  return 1
}

function beta(x: number): number {
  return x + 1
}

export class Widget {
  render(): string {
    return \"w\"
  }
  update(): void {
    this.x = 1
  }
}

export const VERSION = \"1.0\"
const double = (n: number) => n * 2
";
        let chunks = super::ast::try_chunk_ast(Path::new("fixture.ts"), src, 1400)
            .expect("TS fixture must parse via the AST chunker");

        let symbols: Vec<String> = chunks.iter().filter_map(|c| c.symbol.clone()).collect();
        // Free functions and methods are captured by name.
        assert!(
            symbols.contains(&"alpha".to_string()),
            "alpha ({symbols:?})"
        );
        assert!(symbols.contains(&"beta".to_string()), "beta ({symbols:?})");
        assert!(
            symbols.contains(&"render".to_string()),
            "method render ({symbols:?})"
        );
        assert!(
            symbols.contains(&"update".to_string()),
            "method update ({symbols:?})"
        );
        // The arrow-function `const` is a function → captured by its binding name.
        assert!(
            symbols.contains(&"double".to_string()),
            "arrow const ({symbols:?})"
        );

        // The class shell itself is NOT a function → never emitted as a chunk.
        assert!(
            !symbols.contains(&"Widget".to_string()),
            "no class-shell chunk"
        );

        // No non-function code leaks in: the import line and the plain `VERSION` const
        // must not appear in ANY chunk's text.
        let all_text: String = chunks
            .iter()
            .map(|c| c.text.as_str())
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            !all_text.contains("import { helper }"),
            "import must not be indexed"
        );
        assert!(
            !all_text.contains("VERSION"),
            "plain const must not be indexed"
        );
    }

    /// Rust function-only chunking: free functions, impl methods, and nested functions are
    /// captured; const/static/mod/struct/type items are NOT (the bug that made `duplicates`
    /// report the whole codebase).
    #[cfg(feature = "ast")]
    #[test]
    fn ast_rust_captures_only_functions() {
        // sai-noduplicate: per-language AST capture test (Rust), mirror of the Go case
        use std::path::Path;

        let src = "\
const DEFAULT_BACKEND: &str = \"qdrant\";
mod config;
type Alias = u64;

struct Widget { x: u64 }

fn free_fn(a: u64) -> u64 {
    fn nested(b: u64) -> u64 { b + 1 }
    nested(a)
}

impl Widget {
    fn method(&self) -> u64 {
        self.x
    }
}
";
        let chunks = super::ast::try_chunk_ast(Path::new("fixture.rs"), src, 1400)
            .expect("Rust fixture must parse via the AST chunker");
        let symbols: Vec<String> = chunks.iter().filter_map(|c| c.symbol.clone()).collect();

        assert!(
            symbols.contains(&"free_fn".to_string()),
            "free_fn ({symbols:?})"
        );
        assert!(
            symbols.contains(&"nested".to_string()),
            "nested fn ({symbols:?})"
        );
        assert!(
            symbols.contains(&"method".to_string()),
            "impl method ({symbols:?})"
        );

        // Non-function items must never be captured…
        for forbidden in ["DEFAULT_BACKEND", "config", "Alias", "Widget"] {
            assert!(
                !symbols.iter().any(|s| s == forbidden),
                "{forbidden} must not be a chunk symbol ({symbols:?})"
            );
        }
        // …nor appear as text (no remainder pass): the const/mod/type/struct lines are gone.
        let all_text: String = chunks
            .iter()
            .map(|c| c.text.as_str())
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            !all_text.contains("DEFAULT_BACKEND"),
            "const text must not be indexed"
        );
        assert!(
            !all_text.contains("struct Widget"),
            "struct decl must not be indexed"
        );
    }

    /// Go function-only chunking: top-level `func` declarations and methods (with a receiver)
    /// are captured; type/const/var/import/struct declarations are NOT.
    #[cfg(feature = "ast")]
    #[test]
    fn ast_go_captures_only_functions() {
        // sai-noduplicate: per-language AST capture test (Go), mirror of the Rust case
        use std::path::Path;

        let src = "\
package main

import \"fmt\"

const DefaultBackend = \"qdrant\"

type Widget struct {
\tX uint64
}

func FreeFn(a int) int {
\treturn a + 1
}

func (w Widget) Method() uint64 {
\treturn w.X
}
";
        let chunks = super::ast::try_chunk_ast(Path::new("fixture.go"), src, 1400)
            .expect("Go fixture must parse via the AST chunker");
        let symbols: Vec<String> = chunks.iter().filter_map(|c| c.symbol.clone()).collect();

        assert!(
            symbols.contains(&"FreeFn".to_string()),
            "FreeFn ({symbols:?})"
        );
        assert!(
            symbols.contains(&"Method".to_string()),
            "receiver method ({symbols:?})"
        );

        // Non-function declarations must never be captured…
        for forbidden in ["DefaultBackend", "Widget", "main"] {
            assert!(
                !symbols.iter().any(|s| s == forbidden),
                "{forbidden} must not be a chunk symbol ({symbols:?})"
            );
        }
        // …nor appear as text (no remainder pass).
        let all_text: String = chunks
            .iter()
            .map(|c| c.text.as_str())
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            !all_text.contains("DefaultBackend"),
            "const text must not be indexed"
        );
        assert!(
            !all_text.contains("type Widget"),
            "struct decl must not be indexed"
        );
        assert!(!all_text.contains("import"), "import must not be indexed");
    }

    /// Python function-only chunking: free functions, class methods, nested functions,
    /// `async def`s, and decorated functions are captured; module-level constants, class
    /// declarations, and `lambda` bindings are NOT.
    #[cfg(feature = "ast")]
    #[test]
    fn ast_python_captures_only_functions() {
        // sai-noduplicate: per-language AST capture test (Python), mirror of the Rust/Go cases
        use std::path::Path;

        let src = "\
DEFAULT_BACKEND = \"qdrant\"

square = lambda x: x * x

class Widget:
    def method(self):
        return self.x

def free_fn(a):
    def nested(b):
        return b + 1
    return nested(a)

async def fetch_data(url):
    return await get(url)

@cached
def decorated(n):
    return n * 2
";
        let chunks = super::ast::try_chunk_ast(Path::new("fixture.py"), src, 1400)
            .expect("Python fixture must parse via the AST chunker");
        let symbols: Vec<String> = chunks.iter().filter_map(|c| c.symbol.clone()).collect();

        for expected in ["method", "free_fn", "nested", "fetch_data", "decorated"] {
            assert!(
                symbols.iter().any(|s| s == expected),
                "{expected} ({symbols:?})"
            );
        }

        // Non-function bindings must never be captured…
        for forbidden in ["DEFAULT_BACKEND", "Widget", "square"] {
            assert!(
                !symbols.iter().any(|s| s == forbidden),
                "{forbidden} must not be a chunk symbol ({symbols:?})"
            );
        }
        // …nor appear as text (no remainder pass): module-level statements are gone, and a
        // decorated function's chunk starts at `def` (the decorator line is not embedded).
        let all_text: String = chunks
            .iter()
            .map(|c| c.text.as_str())
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            !all_text.contains("DEFAULT_BACKEND"),
            "module constant must not be indexed"
        );
        assert!(
            !all_text.contains("class Widget"),
            "class decl line must not be indexed"
        );
        assert!(!all_text.contains("lambda"), "lambda must not be indexed");
        assert!(
            !all_text.contains("@cached"),
            "decorator line must not be indexed"
        );
    }

    /// AST oversize-split: methods are captured directly (no class qualification), and an
    /// oversized standalone function line-splits into multiple windows that keep its symbol.
    #[cfg(feature = "ast")]
    #[test]
    fn ast_oversized_function_line_splits() {
        use std::path::Path;

        let src = "\
export class Big {
  one(): number {
    return 1
  }
  two(): number {
    return 2
  }
}

export function huge(): number {
  const a = 1
  const b = 2
  const c = 3
  return a + b + c
}
";
        // Tiny cap forces the oversized function over the limit.
        let chunks =
            super::ast::try_chunk_ast(Path::new("big.ts"), src, 30).expect("fixture must parse");
        let symbols: Vec<String> = chunks.iter().filter_map(|c| c.symbol.clone()).collect();

        // Methods are captured directly by their own name (no `Class.` prefix anymore).
        assert!(
            symbols.iter().any(|s| s == "one"),
            "method one ({symbols:?})"
        );
        assert!(
            symbols.iter().any(|s| s == "two"),
            "method two ({symbols:?})"
        );
        // No class-shell chunk.
        assert!(!symbols.iter().any(|s| s == "Big"), "no whole-class chunk");

        // Oversized standalone function line-splits into >1 window, all tagged `huge`.
        let huge_chunks: Vec<_> = chunks
            .iter()
            .filter(|c| c.symbol.as_deref() == Some("huge"))
            .collect();
        assert!(
            huge_chunks.len() > 1,
            "oversized function line-splits into multiple windows ({})",
            huge_chunks.len()
        );
    }

    /// Sync lock: every extension the smart default advertises as AST-preferred
    /// (`config::AST_PREFERRED_EXTS`) must dispatch to a grammar in `try_chunk_ast`.
    /// An entry in one list but not the other would silently line-chunk files the
    /// user was told get AST chunking. Empty source parses error-free in every
    /// grammar, so `Some` here means "extension has a grammar".
    #[cfg(feature = "ast")]
    #[test]
    fn ast_dispatch_covers_all_preferred_extensions() {
        use std::path::PathBuf;
        for ext in crate::config::AST_PREFERRED_EXTS {
            let path = PathBuf::from(format!("fixture.{ext}"));
            assert!(
                super::ast::try_chunk_ast(&path, "", 1400).is_some(),
                "ext '{ext}' is AST-preferred but has no grammar dispatch"
            );
        }
    }

    /// AST fallback: an extension without a tree-sitter grammar (e.g. Java) returns `None`
    /// so the caller uses the line chunker.
    #[cfg(feature = "ast")]
    #[test]
    fn ast_returns_none_for_unsupported_extension() {
        use std::path::Path;
        assert!(
            super::ast::try_chunk_ast(Path::new("x.java"), "class X { void f() {} }\n", 1400)
                .is_none()
        );
    }

    /// AST chunker on a file with NO functions (only imports + plain statements). Since the
    /// index is function-only, this produces zero chunks — nothing to compare for dedup.
    #[cfg(feature = "ast")]
    #[test]
    fn ast_no_functions_yields_no_chunks() {
        use std::path::Path;

        let src = "\
import { foo } from './foo';
import bar from './bar';

const x = 1;
let y = 2;
foo();
bar();
";

        let chunks =
            super::ast::try_chunk_ast(Path::new("no-fns.ts"), src, 1400).expect("should parse");

        assert!(
            chunks.is_empty(),
            "a file with no functions must produce no chunks (got {})",
            chunks.len()
        );
    }

    /// The per-chunk `language` label is derived from the file extension (lowercased),
    /// so a mixed `--ext ts,tsx` walk stamps each file with its own label.
    #[test]
    fn language_for_path_lowercases_extension() {
        use std::path::Path;
        assert_eq!(super::language_for_path(Path::new("a/b/Foo.ts")), "ts");
        assert_eq!(super::language_for_path(Path::new("a/b/Bar.TSX")), "tsx");
        assert_eq!(super::language_for_path(Path::new("Makefile")), "");
    }

    /// `build_chunks` stamps each chunk with the file's own derived language — a `.tsx`
    /// file gets "tsx" even though the same plan also indexes `.ts`.
    #[test]
    fn build_chunks_stamps_per_file_language() {
        use std::path::Path;
        let plan = crate::config::test_support::minimal_plan();
        let src = "export function widget() { return 1 }\n";
        let chunks = super::build_chunks(&plan, Path::new("ui/Widget.tsx"), "ui/Widget.tsx", src);
        assert!(!chunks.is_empty(), "fixture must produce chunks");
        assert!(
            chunks.iter().all(|c| c.language == "tsx"),
            "every chunk from a .tsx file is labelled \"tsx\""
        );
    }

    /// `scan_markers` detects each marker (case-insensitively), reports neither when the
    /// span is clean, respects the on/off flags, and tolerates out-of-range spans.
    #[test]
    fn scan_markers_detects_respects_flags_and_ranges() {
        let lines = vec![
            "fn a() {",                  // 1
            "  // sai-NoIndexing keep",  // 2 (uppercase mix)
            "  foo();",                  // 3
            "}",                         // 4
            "fn b() {",                  // 5
            "  // SAI-NODUPLICATE here", // 6 (uppercase)
            "}",                         // 7
            "fn c() { ok() }",           // 8 (no markers)
        ];

        // Marker found within the span (case-insensitive).
        assert_eq!(super::scan_markers(&lines, 1, 4, true, true), (true, false));
        assert_eq!(super::scan_markers(&lines, 5, 7, true, true), (false, true));
        // No marker in the span → neither.
        assert_eq!(
            super::scan_markers(&lines, 8, 8, true, true),
            (false, false)
        );

        // Flags gate detection: noindex off → not reported even though present.
        assert_eq!(
            super::scan_markers(&lines, 1, 4, false, true),
            (false, false)
        );
        // nodup off → not reported.
        assert_eq!(
            super::scan_markers(&lines, 5, 7, true, false),
            (false, false)
        );
        // Both off short-circuits.
        assert_eq!(
            super::scan_markers(&lines, 1, 7, false, false),
            (false, false)
        );

        // Out-of-range / empty spans are safe (no panic, no detection).
        assert_eq!(
            super::scan_markers(&lines, 100, 200, true, true),
            (false, false)
        );
        assert_eq!(
            super::scan_markers(&lines, 5, 5, true, true),
            (false, false)
        );
    }

    /// `build_chunks` (lines chunker) drops a span carrying `sai-noindexing` entirely,
    /// marks a span carrying `sai-noduplicate` as `no_duplicate`, and leaves a plain
    /// span unmarked.
    #[test]
    fn build_chunks_honors_markers() {
        use std::path::Path;
        let mut plan = crate::config::test_support::minimal_plan();
        plan.chunker = "lines".to_string();
        plan.strip_comments = true;
        plan.honor_noindex_marker = true;
        plan.honor_noduplicate_marker = true;

        // noindex: the whole single-window file is dropped.
        let src_noindex = "export function a() {\n  // sai-noindexing\n  return 1\n}\n";
        let chunks = super::build_chunks(&plan, Path::new("a.ts"), "a.ts", src_noindex);
        assert!(chunks.is_empty(), "a sai-noindexing chunk is never stored");

        // noduplicate: indexed, flagged.
        let src_nodup = "export function b() {\n  // sai-noduplicate\n  return 2\n}\n";
        let chunks = super::build_chunks(&plan, Path::new("b.ts"), "b.ts", src_nodup);
        assert!(
            !chunks.is_empty(),
            "a sai-noduplicate chunk is still stored"
        );
        assert!(
            chunks.iter().all(|c| c.no_duplicate),
            "the chunk is flagged no_duplicate"
        );

        // plain: indexed, not flagged.
        let src_plain = "export function c() {\n  return 3\n}\n";
        let chunks = super::build_chunks(&plan, Path::new("c.ts"), "c.ts", src_plain);
        assert!(!chunks.is_empty(), "a plain chunk is stored");
        assert!(
            chunks.iter().all(|c| !c.no_duplicate),
            "a plain chunk is not flagged no_duplicate"
        );
    }

    /// Toggling the honor flags off disables detection: a `sai-noindexing` span is kept
    /// and a `sai-noduplicate` span is not flagged.
    #[test]
    fn build_chunks_marker_flags_off_disable_detection() {
        use std::path::Path;
        let mut plan = crate::config::test_support::minimal_plan();
        plan.chunker = "lines".to_string();
        plan.honor_noindex_marker = false;
        plan.honor_noduplicate_marker = false;

        let src_noindex = "export function a() {\n  // sai-noindexing\n  return 1\n}\n";
        let chunks = super::build_chunks(&plan, Path::new("a.ts"), "a.ts", src_noindex);
        assert!(
            !chunks.is_empty(),
            "with honor_noindex_marker off the chunk is kept"
        );

        let src_nodup = "export function b() {\n  // sai-noduplicate\n  return 2\n}\n";
        let chunks = super::build_chunks(&plan, Path::new("b.ts"), "b.ts", src_nodup);
        assert!(!chunks.is_empty(), "chunk present");
        assert!(
            chunks.iter().all(|c| !c.no_duplicate),
            "with honor_noduplicate_marker off the chunk is not flagged"
        );
    }
}
