//! Walk / filter / chunk / strip logic that turns a `Plan` into `Vec<CodeChunk>`
//! work items. Backend-free: this module never constructs or touches a backend.

use std::collections::HashMap;
use std::hash::{Hash, Hasher};
use std::path::Path;
use twox_hash::XxHash64;
use walkdir::WalkDir;

use crate::config::Plan;
use crate::vectordbs::CodeChunk;

/// Extensions whose comments are stripped (C-family `//` and `/* */`). Covers TS now, Go later.
const CSTYLE_EXTS: &[&str] = &[
    "ts", "tsx", "js", "jsx", "mjs", "cjs", "go", "rs", "java", "c", "h", "cc", "cpp", "hpp", "cs",
    "kt", "swift", "scala",
];
/// Secondary line guard for the line-window chunker. The primary size bound is
/// `plan.max_chunk_chars` (model-aware); this caps the line count of a single window.
const MAX_LINES: usize = 60;
const OVERLAP_LINES: usize = 8;
/// First N bytes scanned for an autogenerated marker.
const MARKER_SCAN_BYTES: usize = 600;
/// Case-insensitive substrings that mark an autogenerated file.
const GENERATED_MARKERS: &[&str] = &[
    "do not edit",
    "@generated",
    "code generated",
    "auto-generated",
    "autogenerated",
    "this file is generated",
];

/// One embeddable slice of a source file.
struct Chunk {
    start_line: usize,
    end_line: usize,
    text: String,
    /// Captured symbol name (AST chunker only). `None` for line-window chunks.
    symbol: Option<String>,
}

/// Read → strip comments → chunk → build code chunks for one file (no generated-marker check here).
///
/// Comments are stripped BEFORE chunking (so only code is embedded). The AST chunker
/// therefore parses the comment-stripped text — acceptable, since stripping preserves
/// line count and code structure.
pub fn build_chunks(plan: &Plan, path: &Path, rel: &str, raw: &str) -> Vec<CodeChunk> {
    let content = if plan.strip_comments && is_cstyle(path) {
        strip_c_comments(raw)
    } else {
        raw.to_string()
    };
    chunk_content(plan, path, &content)
        .into_iter()
        .map(|c| CodeChunk {
            id: point_id(rel, c.start_line),
            path: rel.to_string(),
            language: plan.language.clone(),
            start_line: c.start_line,
            end_line: c.end_line,
            text: c.text,
            symbol: c.symbol,
        })
        .collect()
}

/// Dispatch to the configured chunker. `lines` (default) is the line-window chunker;
/// `ast` is the tree-sitter chunker (feature-gated). `ast` falls back to the line
/// chunker for any file it cannot parse (non-TS ext, or a parse error).
fn chunk_content(plan: &Plan, path: &Path, content: &str) -> Vec<Chunk> {
    match plan.chunker.as_str() {
        "lines" => chunk_lines(content, plan.max_chunk_chars),
        "ast" => chunk_ast(path, content, plan.max_chunk_chars),
        // build_plan does not validate the value, so guard here. Unknown → line chunker.
        _ => chunk_lines(content, plan.max_chunk_chars),
    }
}

/// AST chunker entry point. When the `ast` feature is compiled in, parse TS/TSX and
/// emit symbol-aware chunks; for any other extension, or on a parse failure, fall back
/// to the line chunker. When the feature is NOT compiled in, selecting `chunker: ast`
/// is a hard error (mirrors the embedder/backend gating).
#[cfg(feature = "ast")]
fn chunk_ast(path: &Path, content: &str, cap: usize) -> Vec<Chunk> {
    ast::chunk_ast_ts(path, content, cap).unwrap_or_else(|| chunk_lines(content, cap))
}

#[cfg(not(feature = "ast"))]
fn chunk_ast(_path: &Path, _content: &str, _cap: usize) -> Vec<Chunk> {
    // The plan validates this earlier (see `ensure_chunker_available`), so this is
    // unreachable in practice; keep it total for safety.
    Vec::new()
}

/// Reject `chunker: ast` when the `ast` feature was not compiled in — a clear,
/// actionable error that mirrors the backend/embedder feature gating. Call once at
/// startup before any indexing.
pub fn ensure_chunker_available(plan: &Plan) -> anyhow::Result<()> {
    match plan.chunker.as_str() {
        "lines" => Ok(()),
        "ast" => {
            #[cfg(feature = "ast")]
            {
                Ok(())
            }
            #[cfg(not(feature = "ast"))]
            {
                anyhow::bail!(
                    "chunker 'ast' selected but this binary was built without the 'ast' feature (rebuild with --features ast)"
                )
            }
        }
        other => anyhow::bail!("unknown chunker '{other}' (expected 'lines' or 'ast')"),
    }
}

/// Walk the root and produce all `CodeChunk` work items for the plan, plus the
/// count of files skipped by config. Backend-free.
pub fn collect_chunks(plan: &Plan) -> (Vec<CodeChunk>, usize, usize) {
    let mut chunks: Vec<CodeChunk> = Vec::new();
    let mut files = 0usize;
    let mut skipped = 0usize;

    for entry in WalkDir::new(&plan.root)
        .into_iter()
        .filter_entry(|e| !is_pruned_dir(e.path(), plan))
        .filter_map(std::result::Result::ok)
    {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if !has_wanted_ext(path, &plan.ext) {
            continue;
        }
        let rel = path.to_string_lossy().to_string();
        let key = rel.trim_start_matches("./");
        // include is an allow-list: when active, a non-match is skipped; exclude then wins.
        if !plan.passes_globs(key) {
            skipped += 1;
            continue;
        }

        let raw = match std::fs::read_to_string(path) {
            Ok(c) => c,
            Err(_) => continue, // skip binary / non-utf8
        };
        if plan.skip_generated && is_generated(&raw) {
            skipped += 1;
            continue;
        }

        let file_chunks = build_chunks(plan, path, key, &raw);
        if file_chunks.is_empty() {
            continue;
        }
        files += 1;
        chunks.extend(file_chunks);
    }

    (chunks, files, skipped)
}

/// Walk + report inclusions/exclusions without touching any backend.
pub fn dry_run(plan: &Plan) {
    let mut included: Vec<String> = Vec::new();
    let mut excluded: Vec<(String, &'static str)> = Vec::new();

    for entry in WalkDir::new(&plan.root)
        .into_iter()
        .filter_entry(|e| !is_pruned_dir(e.path(), plan))
        .filter_map(std::result::Result::ok)
    {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if !has_wanted_ext(path, &plan.ext) {
            continue;
        }
        let rel = path.to_string_lossy().to_string();
        let key = rel.trim_start_matches("./");
        if plan.include_active && !plan.include.is_match(key) {
            excluded.push((rel, "not-included"));
            continue;
        }
        if plan.exclude.is_match(key) {
            excluded.push((rel, "glob"));
            continue;
        }
        if plan.skip_generated {
            if let Ok(content) = std::fs::read_to_string(path) {
                if is_generated(&content) {
                    excluded.push((rel, "generated-marker"));
                    continue;
                }
            }
        }
        included.push(rel);
    }

    println!("DRY RUN — root '{}', ext {}", plan.root, plan.ext.join("/"));
    println!("collection '{}', model '{}'", plan.collection, plan.model);
    println!(
        "strip_comments: {}   skip_generated_marker: {}",
        plan.strip_comments, plan.skip_generated
    );
    let mut pruned: Vec<&str> = plan.exclude_dirs.iter().map(String::as_str).collect();
    pruned.sort_unstable();
    println!("pruned dirs: {}", pruned.join(", "));
    println!(
        "\nWOULD INDEX: {} file(s)   EXCLUDED: {} file(s)",
        included.len(),
        excluded.len()
    );

    let mut by_reason: HashMap<&str, usize> = HashMap::new();
    for (_, reason) in &excluded {
        *by_reason.entry(reason).or_default() += 1;
    }
    for (reason, n) in &by_reason {
        println!("  excluded by {reason}: {n}");
    }

    println!("\nsample excluded:");
    for (rel, reason) in excluded.iter().take(15) {
        println!("  - {rel}  [{reason}]");
    }
    println!("\nsample included:");
    for rel in included.iter().take(15) {
        println!("  + {rel}");
    }
}

/// Deterministic u64 id from path + chunk start, so re-runs update points in place.
///
/// Uses `XxHash64` with a fixed seed (0) so IDs are STABLE across builds and
/// machines (unlike `DefaultHasher`, whose algorithm is unspecified). This is
/// shared by every backend so Qdrant and DuckDB key the same chunk identically.
///
/// NOTE: switching off `DefaultHasher` changes existing Qdrant point IDs — a
/// one-time `flush` / `--recreate` is needed after this change.
pub fn point_id(path: &str, start_line: usize) -> u64 {
    let mut hasher = XxHash64::with_seed(0);
    path.hash(&mut hasher);
    start_line.hash(&mut hasher);
    hasher.finish()
}

/// Split whole-file content into line windows bounded by MAX_LINES / `cap` chars with
/// small overlap. The classic chunker (`chunker: lines`); all chunks have `symbol: None`.
fn chunk_lines(content: &str, cap: usize) -> Vec<Chunk> {
    let lines: Vec<&str> = content.lines().collect();
    chunk_line_range(&lines, 0, lines.len(), cap)
}

/// Line-window chunker over a sub-range `[from, to)` of `lines` (0-based), emitting
/// 1-based `start_line`/`end_line` that account for the range offset. Shared by the
/// whole-file [`chunk_lines`] and the AST chunker's oversize/remainder line-splitting,
/// so window sizing and overlap can never drift between the two paths.
fn chunk_line_range(lines: &[&str], from: usize, to: usize, cap: usize) -> Vec<Chunk> {
    let mut chunks = Vec::new();
    let mut i = from;
    while i < to {
        let mut j = i;
        let mut chars = 0usize;
        while j < to && (j - i) < MAX_LINES && chars < cap {
            chars += lines[j].len() + 1;
            j += 1;
        }
        let text = lines[i..j].join("\n");
        if !text.trim().is_empty() {
            chunks.push(Chunk {
                start_line: i + 1,
                end_line: j,
                text,
                symbol: None,
            });
        }
        if j >= to {
            break;
        }
        i = if j > i + OVERLAP_LINES {
            j - OVERLAP_LINES
        } else {
            j
        };
    }
    chunks
}

fn is_cstyle(path: &Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| CSTYLE_EXTS.contains(&e))
}

/// Remove C-family comments (`//` line, `/* */` block) while preserving string and
/// template literals AND the exact newline count (so payload line numbers stay accurate).
///
/// Known limitation: regex literals are not tracked, so a `//` *inside* a regex literal
/// would be treated as a line comment. This is vanishingly rare in real code.
fn strip_c_comments(src: &str) -> String {
    #[derive(PartialEq)]
    enum State {
        Normal,
        Line,
        Block,
        Dq,  // "double"
        Sq,  // 'single'
        Tpl, // `template`
    }
    let chars: Vec<char> = src.chars().collect();
    let n = chars.len();
    let mut out = String::with_capacity(src.len());
    let mut state = State::Normal;
    let mut i = 0;
    while i < n {
        let c = chars[i];
        let next = if i + 1 < n { chars[i + 1] } else { '\0' };
        match state {
            State::Normal => match (c, next) {
                ('/', '/') => {
                    state = State::Line;
                    i += 2;
                }
                ('/', '*') => {
                    state = State::Block;
                    i += 2;
                }
                ('"', _) => {
                    out.push(c);
                    state = State::Dq;
                    i += 1;
                }
                ('\'', _) => {
                    out.push(c);
                    state = State::Sq;
                    i += 1;
                }
                ('`', _) => {
                    out.push(c);
                    state = State::Tpl;
                    i += 1;
                }
                _ => {
                    out.push(c);
                    i += 1;
                }
            },
            State::Line => {
                // Drop everything up to (not including) the newline.
                if c == '\n' {
                    out.push('\n');
                    state = State::Normal;
                }
                i += 1;
            }
            State::Block => {
                if c == '*' && next == '/' {
                    state = State::Normal;
                    i += 2;
                } else {
                    if c == '\n' {
                        out.push('\n'); // keep line count stable
                    }
                    i += 1;
                }
            }
            State::Dq | State::Sq | State::Tpl => {
                out.push(c);
                if c == '\\' && i + 1 < n {
                    out.push(chars[i + 1]); // copy escaped char verbatim
                    i += 2;
                    continue;
                }
                let closes = match state {
                    State::Dq => c == '"',
                    State::Sq => c == '\'',
                    State::Tpl => c == '`',
                    _ => false,
                };
                if closes {
                    state = State::Normal;
                }
                i += 1;
            }
        }
    }
    out
}

/// True if the file's opening bytes carry an autogenerated marker.
pub fn is_generated(content: &str) -> bool {
    let head = content[..content.len().min(MARKER_SCAN_BYTES)].to_lowercase();
    GENERATED_MARKERS.iter().any(|m| head.contains(m))
}

fn is_pruned_dir(path: &Path, plan: &Plan) -> bool {
    path.file_name()
        .and_then(|n| n.to_str())
        .is_some_and(|n| plan.exclude_dirs.contains(n))
}

pub fn has_wanted_ext(path: &Path, wanted: &[String]) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| wanted.iter().any(|w| w == e))
}

/// AST chunker (tree-sitter, TypeScript/TSX). Backend-free, like the rest of this module.
///
/// Strategy:
/// - Parse the file with the TS (or TSX for `.tsx`) grammar. A root parse error → `None`
///   so the caller falls back to the line chunker. Only `.ts`/`.tsx` are AST-handled; any
///   other extension also returns `None`.
/// - A tree-sitter [`Query`] captures top-level declarations (function / arrow-or-function
///   `const` / class / interface / type-alias) with their identifier as the symbol, plus
///   `method_definition`s (used only when recursing into an oversized class).
/// - For each top-level node: text length ≤ `cap` → ONE chunk (symbol + node line range).
///   Oversized class → one chunk per method; oversized function/other → line-split that
///   node's span via the shared line chunker.
/// - Lines NOT covered by any captured top-level node (imports, top-level statements) are
///   gathered into "remainder" chunks via the line chunker (`symbol: None`). Nothing is
///   silently dropped.
#[cfg(feature = "ast")]
mod ast {
    use super::{Chunk, MAX_LINES, chunk_line_range};
    use std::path::Path;
    use tree_sitter::{Node, Parser, Query, QueryCursor, StreamingIterator};

    /// Captures every chunkable declaration plus class methods. `@item` is the node to
    /// chunk; `@name` is its identifier (the symbol). `@method` marks methods so an
    /// oversized class can be split into per-method chunks.
    const QUERY_SRC: &str = r#"
(function_declaration name: (identifier) @name) @item
(class_declaration name: (type_identifier) @name) @item
(interface_declaration name: (type_identifier) @name) @item
(type_alias_declaration name: (type_identifier) @name) @item
(lexical_declaration
  (variable_declarator
    name: (identifier) @name
    value: [(arrow_function) (function_expression)])) @item
(method_definition name: (property_identifier) @name) @method
"#;

    /// One captured AST node: byte span, line span (1-based), kind, and symbol.
    struct Item {
        kind: String,
        symbol: Option<String>,
        start_byte: usize,
        end_byte: usize,
        start_line: usize, // 1-based
        end_line: usize,   // 1-based, inclusive
        is_method: bool,
    }

    /// Returns `Some(chunks)` for parseable TS/TSX, or `None` to signal the caller should
    /// fall back to the line chunker (unsupported extension or a root parse error).
    pub fn chunk_ast_ts(path: &Path, content: &str, cap: usize) -> Option<Vec<Chunk>> {
        let ext = path.extension().and_then(|e| e.to_str())?;
        let language: tree_sitter::Language = match ext {
            "tsx" => tree_sitter_typescript::LANGUAGE_TSX.into(),
            "ts" => tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(),
            _ => return None,
        };

        let mut parser = Parser::new();
        parser.set_language(&language).ok()?;
        let tree = parser.parse(content, None)?;
        let root = tree.root_node();
        // A root-level error means the parse is unreliable → fall back.
        if root.is_error() || root.kind() == "ERROR" {
            return None;
        }

        let query = Query::new(&language, QUERY_SRC).ok()?;
        let name_idx = query.capture_index_for_name("name")?;
        let item_idx = query.capture_index_for_name("item")?;
        let method_idx = query.capture_index_for_name("method")?;

        let src = content.as_bytes();
        let mut items: Vec<Item> = Vec::new();
        let mut cursor = QueryCursor::new();
        let mut matches = cursor.matches(&query, root, src);
        while let Some(m) = matches.next() {
            let mut node: Option<Node> = None;
            let mut symbol: Option<String> = None;
            let mut is_method = false;
            for cap in m.captures {
                if cap.index == item_idx {
                    node = Some(cap.node);
                } else if cap.index == method_idx {
                    node = Some(cap.node);
                    is_method = true;
                } else if cap.index == name_idx {
                    symbol = cap.node.utf8_text(src).ok().map(str::to_string);
                }
            }
            if let Some(n) = node {
                items.push(Item {
                    kind: n.kind().to_string(),
                    symbol,
                    start_byte: n.start_byte(),
                    end_byte: n.end_byte(),
                    start_line: n.start_position().row + 1,
                    end_line: n.end_position().row + 1,
                    is_method,
                });
            }
        }

        let lines: Vec<&str> = content.lines().collect();
        let total_lines = lines.len();
        let mut chunks: Vec<Chunk> = Vec::new();
        // Track which 1-based lines a captured top-level node already covers, so the
        // remainder pass can chunk only the gaps (imports / top-level statements).
        let mut covered = vec![false; total_lines + 2];

        // Top-level items only (methods are handled when recursing into a class).
        let mut top: Vec<&Item> = items.iter().filter(|it| !it.is_method).collect();
        top.sort_by_key(|it| it.start_byte);

        for it in &top {
            mark_covered(&mut covered, it.start_line, it.end_line);
            let len = it.end_byte.saturating_sub(it.start_byte);
            if len <= cap {
                let text = node_text(&lines, it.start_line, it.end_line);
                if !text.trim().is_empty() {
                    chunks.push(Chunk {
                        start_line: it.start_line,
                        end_line: it.end_line,
                        text,
                        symbol: it.symbol.clone(),
                    });
                }
                continue;
            }
            // Oversized. A class splits into per-method chunks; anything else is
            // line-split over its own span (reusing the shared line chunker).
            if it.kind == "class_declaration" {
                let methods: Vec<&Item> = items
                    .iter()
                    .filter(|m| {
                        m.is_method && m.start_byte >= it.start_byte && m.end_byte <= it.end_byte
                    })
                    .collect();
                if methods.is_empty() {
                    chunks.extend(line_split_node(&lines, it, cap, it.symbol.clone()));
                } else {
                    for m in methods {
                        let mname = qualified_method(it.symbol.as_deref(), m.symbol.as_deref());
                        if m.end_byte.saturating_sub(m.start_byte) <= cap {
                            let text = node_text(&lines, m.start_line, m.end_line);
                            if !text.trim().is_empty() {
                                chunks.push(Chunk {
                                    start_line: m.start_line,
                                    end_line: m.end_line,
                                    text,
                                    symbol: Some(mname),
                                });
                            }
                        } else {
                            chunks.extend(line_split_node(&lines, m, cap, Some(mname)));
                        }
                    }
                }
            } else {
                chunks.extend(line_split_node(&lines, it, cap, it.symbol.clone()));
            }
        }

        // Remainder: contiguous runs of uncovered lines → line chunks (symbol: None).
        let mut i = 1usize;
        while i <= total_lines {
            if covered[i] {
                i += 1;
                continue;
            }
            let start = i;
            while i <= total_lines && !covered[i] {
                i += 1;
            }
            let end = i - 1; // inclusive 1-based
            // `chunk_line_range` is 0-based half-open over the full `lines` slice.
            chunks.extend(chunk_line_range(&lines, start - 1, end, cap));
        }

        chunks.sort_by_key(|c| c.start_line);
        Some(chunks)
    }

    /// Mark 1-based lines `[start, end]` inclusive as covered.
    fn mark_covered(covered: &mut [bool], start: usize, end: usize) {
        for l in start..=end {
            if let Some(slot) = covered.get_mut(l) {
                *slot = true;
            }
        }
    }

    /// Extract the text of a node by its 1-based inclusive line range.
    fn node_text(lines: &[&str], start_line: usize, end_line: usize) -> String {
        let s = start_line.saturating_sub(1);
        let e = end_line.min(lines.len());
        if s >= e {
            return String::new();
        }
        lines[s..e].join("\n")
    }

    /// Line-split an oversized node's own span via the shared line chunker, tagging each
    /// resulting window with the node's symbol so the symbol survives the split.
    fn line_split_node(
        lines: &[&str],
        it: &Item,
        cap: usize,
        symbol: Option<String>,
    ) -> Vec<Chunk> {
        let from = it.start_line.saturating_sub(1);
        let to = it.end_line.min(lines.len());
        let _ = MAX_LINES; // documents that the line guard still applies inside the split
        chunk_line_range(lines, from, to, cap)
            .into_iter()
            .map(|mut c| {
                c.symbol = symbol.clone();
                c
            })
            .collect()
    }

    /// `Class.method` when both names are known, else whichever is known.
    fn qualified_method(class: Option<&str>, method: Option<&str>) -> String {
        match (class, method) {
            (Some(c), Some(m)) => format!("{c}.{m}"),
            (None, Some(m)) => m.to_string(),
            (Some(c), None) => c.to_string(),
            (None, None) => String::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_line_and_block_keeps_strings_and_linecount() {
        let src = "// gone\n\
                   const url = \"http://example.com\" // trailing\n\
                   /* block\n   spanning */\n\
                   const tpl = `keep ${a} and // not a comment`\n\
                   const s = \"a // b in string\"\n\
                   fn() // end\n";
        let out = strip_c_comments(src);
        // line count preserved (payload line numbers stay valid)
        assert_eq!(src.lines().count(), out.lines().count());
        // url inside a string keeps its `//`
        assert!(out.contains("\"http://example.com\""));
        // `//` inside a normal string is not treated as a comment
        assert!(out.contains("\"a // b in string\""));
        // template literal content (incl. its `//`) is preserved verbatim
        assert!(out.contains("`keep ${a} and // not a comment`"));
        // actual comments are gone
        assert!(!out.contains("gone"));
        assert!(!out.contains("trailing"));
        assert!(!out.contains("spanning"));
        assert!(!out.contains("end"));
        // code survives
        assert!(out.contains("const url ="));
        assert!(out.contains("fn()"));
    }

    #[test]
    fn point_id_is_stable_and_deterministic() {
        // Same inputs ⇒ same id (so re-runs update points in place).
        assert_eq!(point_id("src/foo.ts", 1), point_id("src/foo.ts", 1));
        // Different path or line ⇒ different id.
        assert_ne!(point_id("src/foo.ts", 1), point_id("src/bar.ts", 1));
        assert_ne!(point_id("src/foo.ts", 1), point_id("src/foo.ts", 2));
        // Pinned value: XxHash64(seed=0) over path+start_line must not drift across
        // builds/machines. If this fails, the ID algorithm changed (re-index needed).
        assert_eq!(point_id("src/foo.ts", 1), 10293058119199652890_u64);
    }

    #[test]
    fn handles_escaped_quotes() {
        let src = "const s = \"he said \\\"hi\\\" // x\" // real comment\n";
        let out = strip_c_comments(src);
        assert!(out.contains("\"he said \\\"hi\\\" // x\""));
        assert!(!out.contains("real comment"));
    }

    /// The line chunker honors the char cap: a tiny cap forces many small windows;
    /// every emitted window is within the cap's chars (modulo the always-include-one-line
    /// rule for a single oversized line).
    #[test]
    fn line_chunker_respects_char_cap() {
        // 20 short lines of ~5 chars each.
        let content = (0..20)
            .map(|i| format!("ln{i:02}"))
            .collect::<Vec<_>>()
            .join("\n");
        let big = chunk_lines(&content, 1400);
        let small = chunk_lines(&content, 12); // ~2 lines per window
        assert_eq!(
            big.len(),
            1,
            "1400-char cap fits the whole file in one chunk"
        );
        assert!(
            small.len() > big.len(),
            "a 12-char cap must produce more, smaller windows ({} vs {})",
            small.len(),
            big.len()
        );
        // Each small window (beyond its first line) stays at/under the cap.
        for c in &small {
            let lines = c.text.lines().count();
            assert!(lines <= MAX_LINES);
            assert!(c.symbol.is_none(), "line chunks have no symbol");
        }
    }

    /// AST chunker over a representative TS fixture: ≥2 functions + 1 class with methods
    /// + a top-level import and const. Asserts (a) one chunk per function with the right
    /// symbol, (b) a remainder chunk covering the top-level import/const, and (c) nothing
    /// dropped (every line is covered by some chunk).
    #[cfg(feature = "ast")]
    #[test]
    fn ast_chunks_functions_class_methods_and_remainder() {
        use std::path::Path;

        let src = "\
import { helper } from \"./helper\"

export function alpha(): number {
  return 1
}

function beta(x: number): number {
  return x + 1
}

export class Widget {
  render(): string {
    return \"w\"
  }
  update(): void {
    this.x = 1
  }
}

export const VERSION = \"1.0\"
const internal = 7
";
        let chunks = super::ast::chunk_ast_ts(Path::new("fixture.ts"), src, 1400)
            .expect("TS fixture must parse via the AST chunker");

        let symbols: Vec<String> = chunks.iter().filter_map(|c| c.symbol.clone()).collect();
        // (a) one chunk per function with the captured symbol.
        assert!(
            symbols.contains(&"alpha".to_string()),
            "alpha symbol present"
        );
        assert!(symbols.contains(&"beta".to_string()), "beta symbol present");
        // class fits under the cap → one chunk for the whole class (symbol = class name).
        assert!(
            symbols.contains(&"Widget".to_string()),
            "Widget class chunk"
        );

        // (b) remainder chunk(s) (symbol: None) cover the top-level import + consts.
        let remainder_text: String = chunks
            .iter()
            .filter(|c| c.symbol.is_none())
            .map(|c| c.text.clone())
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            remainder_text.contains("import { helper }"),
            "import lands in a remainder chunk"
        );
        assert!(
            remainder_text.contains("VERSION") || symbols.contains(&"VERSION".to_string()),
            "top-level const VERSION is captured or in the remainder"
        );

        // (c) nothing dropped: every source line is covered by some chunk's line range.
        let total = src.lines().count();
        let mut covered = vec![false; total + 1];
        for c in &chunks {
            for l in c.start_line..=c.end_line.min(total) {
                covered[l] = true;
            }
        }
        // Blank lines may be skipped by the chunker; assert every NON-blank line covered.
        let lines: Vec<&str> = src.lines().collect();
        for (idx, line) in lines.iter().enumerate() {
            if !line.trim().is_empty() {
                assert!(covered[idx + 1], "line {} ({line:?}) not covered", idx + 1);
            }
        }
    }

    /// AST oversize-split: with a tiny cap, the class is too big → it splits into
    /// per-method chunks (symbol = `Class.method`); an oversized standalone function
    /// line-splits into multiple windows that keep its symbol.
    #[cfg(feature = "ast")]
    #[test]
    fn ast_oversized_class_splits_into_methods() {
        use std::path::Path;

        let src = "\
export class Big {
  one(): number {
    return 1
  }
  two(): number {
    return 2
  }
}

export function huge(): number {
  const a = 1
  const b = 2
  const c = 3
  return a + b + c
}
";
        // Tiny cap forces the class + function over the limit.
        let chunks =
            super::ast::chunk_ast_ts(Path::new("big.ts"), src, 30).expect("fixture must parse");
        let symbols: Vec<String> = chunks.iter().filter_map(|c| c.symbol.clone()).collect();

        // Class split into per-method chunks → qualified Class.method symbols.
        assert!(
            symbols.iter().any(|s| s == "Big.one"),
            "oversized class split into method one ({symbols:?})"
        );
        assert!(
            symbols.iter().any(|s| s == "Big.two"),
            "oversized class split into method two ({symbols:?})"
        );
        // The whole-class symbol must NOT appear as its own chunk (it was decomposed).
        assert!(
            !symbols.iter().any(|s| s == "Big"),
            "oversized class is not emitted as a single chunk"
        );

        // Oversized standalone function line-splits into >1 window, all tagged `huge`.
        let huge_chunks: Vec<_> = chunks
            .iter()
            .filter(|c| c.symbol.as_deref() == Some("huge"))
            .collect();
        assert!(
            huge_chunks.len() > 1,
            "oversized function line-splits into multiple windows ({})",
            huge_chunks.len()
        );
    }

    /// AST fallback: a non-TS extension returns `None` so the caller uses the line chunker.
    #[cfg(feature = "ast")]
    #[test]
    fn ast_returns_none_for_non_ts_extension() {
        use std::path::Path;
        assert!(super::ast::chunk_ast_ts(Path::new("x.go"), "package main\n", 1400).is_none());
    }
}
