//! Index source files into a vector backend using E5-small.
//!
//! The default backend is Qdrant Cloud with **server-side inference**: embeddings
//! are produced inside the cluster (Inference enabled) by passing
//! `Document::new(text, model)` — no client-side model is loaded.
//!
//! E5 usage note: `intfloat/multilingual-e5-small` is trained with asymmetric
//! prefixes. Stored chunks are embedded as `passage: <code>` and queries as
//! `query: <text>`. The raw code (no prefix) is kept in the payload.
//!
//! What gets pushed is controlled by a YAML config (default `indexer.yaml` in the
//! current directory): excluded dirs, exclude globs, and an autogenerated-marker
//! skip. CLI flags override config values.
//!
//! Connection is read from the environment (never hard-code the token):
//!   QDRANT_URL      e.g. https://<cluster-id>.<region>.aws.cloud.qdrant.io:6334
//!   QDRANT_API_KEY  cluster API key
//!
//! Usage (after `cargo build --release`):
//!   # See exactly what would be indexed/skipped — no network, no upload:
//!   ./target/release/semanticastindexer --root src --dry-run
//!   # TS index:
//!   ./target/release/semanticastindexer --root src --ext ts,tsx --language ts
//!   # Go index later (same collection):
//!   ./target/release/semanticastindexer --root path/to/go --ext go --language go
//!   # Search only:
//!   ./target/release/semanticastindexer \
//!       --query-only --query "where do we create the qdrant collection"

mod config;
mod indexer;
#[cfg(feature = "mcp")]
mod mcp;
// Shared similarity-search core (union-find clustering + find_similar resolution) used by
// BOTH the `similar`/`duplicates` CLI subcommands and the MCP server. Compiled whenever a
// vector backend is available — NOT gated on `mcp`.
#[cfg(any(feature = "duckdb", feature = "qdrant"))]
mod search;
mod vectordbs;
#[cfg(feature = "mcp")]
mod worker;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use std::path::Path;
use std::process::Command;

use config::{DEFAULT_CONFIG, Plan, build_plan};
use vectordbs::{Backend, Hit, factory};

#[derive(Parser, Debug, Clone)]
#[command(
    about = "Index source files into Qdrant via E5-small server-side inference (Document API)"
)]
pub struct Args {
    /// Subcommand. Omitted = full index of --root (the default).
    #[command(subcommand)]
    command: Option<Cmd>,

    /// Root directory to walk for source files.
    #[arg(long, default_value = "src")]
    pub root: String,

    /// File extensions to index (comma-separated, no dots).
    #[arg(long, value_delimiter = ',', default_value = "ts,tsx")]
    pub ext: Vec<String>,

    /// Language label stored in each point's payload.
    #[arg(long, default_value = "ts")]
    pub language: String,

    /// Vector backend: "qdrant" or "duckdb" (overrides config). Global: accepted before
    /// or after a subcommand.
    #[arg(long, global = true)]
    pub backend: Option<String>,

    /// Embedder for the duckdb backend: "ort" or "ollama" (overrides config). Global:
    /// accepted before or after a subcommand.
    #[arg(long, global = true)]
    pub embedder: Option<String>,

    /// Chunker: "lines" or "ast" (tree-sitter). When omitted, we auto-select "ast" for
    /// languages that have AST support (ts/tsx) *if* the binary was built with --features ast.
    /// Explicit --chunker always wins.
    #[arg(long)]
    pub chunker: Option<String>,

    /// Path to the YAML config controlling exclusions. Global: accepted before or after
    /// a subcommand.
    #[arg(long, default_value = DEFAULT_CONFIG, global = true)]
    pub config: String,

    /// Target collection (overrides config). Global: accepted before or after a subcommand.
    #[arg(long, global = true)]
    pub collection: Option<String>,

    /// Inference model (overrides config).
    #[arg(long)]
    pub model: Option<String>,

    /// Optional semantic query to run after indexing (or alone with --query-only).
    #[arg(long)]
    query: Option<String>,

    /// Skip indexing; only run the --query against the existing collection.
    #[arg(long, default_value_t = false)]
    query_only: bool,

    /// Drop and recreate the collection before indexing.
    #[arg(long, default_value_t = false)]
    recreate: bool,

    /// Walk + report what would be indexed/skipped. No network, no upload.
    #[arg(long, default_value_t = false)]
    dry_run: bool,

    /// Number of nearest results to print for a query.
    #[arg(long, default_value_t = 5)]
    pub limit: u64,
}

#[derive(Subcommand, Debug, Clone)]
enum Cmd {
    /// Flush the vector storage: delete the entire collection.
    Flush,
    /// Re-index only changed files (for git hooks): delete each file's points, then upload fresh.
    Sync(SyncArgs),
    /// Run the MCP server (semantic code search for Claude) over stdio.
    /// Honors --backend/--embedder/--collection/--config; defaults to duckdb + ollama.
    /// READ-ONLY by default; pass `--allow-write` to enable the `refresh` write tool.
    #[cfg(feature = "mcp")]
    Mcp(McpArgs),
    /// Codebase-wide near-duplicate clusters (NN edges + union-find), printed
    /// human-readably. Uses stored vectors only (no re-embed). Needs a vector backend +
    /// embedder feature (e.g. --features ort / "ollama,ast").
    #[cfg(any(feature = "duckdb", feature = "qdrant"))]
    Duplicates(DuplicatesArgs),
    /// Nearest neighbours of a code snippet (--code, embedded as a passage) or an existing
    /// indexed chunk (--path --line, stored vector, self-excluded). Needs a vector backend
    /// + embedder feature.
    #[cfg(any(feature = "duckdb", feature = "qdrant"))]
    Similar(SimilarArgs),
}

/// `duplicates` subcommand args. Each threshold knob resolves CLI flag > config
/// (`similarity.*`) > built-in default.
#[cfg(any(feature = "duckdb", feature = "qdrant"))]
#[derive(clap::Args, Debug, Clone)]
struct DuplicatesArgs {
    /// Minimum cosine similarity for an edge to count as a near-duplicate.
    /// Default: config `similarity.duplicate_min_score` (else 0.93).
    #[arg(long)]
    min_score: Option<f32>,
    /// Minimum cluster size to report. Default: config `similarity.duplicate_min_cluster_size` (else 2).
    #[arg(long)]
    min_cluster_size: Option<usize>,
    /// Nearest-neighbour fan-out per chunk. Default: config `similarity.top_k` (else 10).
    #[arg(long)]
    top_k: Option<u64>,
    /// Restrict the scan to paths matching this glob (e.g. "src/utils/**").
    #[arg(long)]
    path_glob: Option<String>,
    /// Max clusters to print (largest first). Default 50.
    #[arg(long)]
    max_clusters: Option<usize>,
}

/// `similar` subcommand args. Provide EXACTLY ONE of --code OR (--path AND --line).
#[cfg(any(feature = "duckdb", feature = "qdrant"))]
#[derive(clap::Args, Debug, Clone)]
struct SimilarArgs {
    /// A code snippet to find neighbours of (embedded as a PASSAGE — code-vs-code space).
    #[arg(long)]
    code: Option<String>,
    /// Path of an existing indexed chunk (use with --line; reuses the stored vector).
    #[arg(long)]
    path: Option<String>,
    /// 1-based start line of an existing indexed chunk (use with --path).
    #[arg(long)]
    line: Option<usize>,
    /// Max results. Default 8.
    #[arg(long, default_value_t = 8)]
    limit: u64,
    /// Drop results scoring below this cosine similarity.
    /// Default: config `similarity.find_similar_min_score` (else 0.85). Pass 0 for raw scores.
    #[arg(long)]
    min_score: Option<f32>,
}

#[cfg(feature = "mcp")]
#[derive(clap::Args, Debug, Clone)]
struct McpArgs {
    /// Open the index WRITABLE and register the `refresh` tool. Without this flag the
    /// server is read-only and `refresh` returns a clear "restart with --allow-write" error.
    #[arg(long, default_value_t = false)]
    allow_write: bool,

    /// Allow the `prepare_mcp_setup` tool to actually execute the mcp-setup script
    /// (can trigger long builds and file modifications). Use with caution.
    #[arg(long, default_value_t = false)]
    allow_setup: bool,
}

#[derive(clap::Args, Debug, Clone)]
struct SyncArgs {
    /// Git revision to diff against; changed set = `<since>..HEAD`.
    #[arg(long, default_value = "HEAD~1")]
    since: String,

    /// Use staged changes (`git diff --cached`) instead of `--since`.
    #[arg(long, default_value_t = false)]
    staged: bool,

    /// Explicit changed file path(s), repeatable. Overrides git detection.
    /// Files that exist are re-indexed; files that are gone are just deleted.
    #[arg(long = "file")]
    files: Vec<String>,
}

#[tokio::main]
async fn main() -> Result<()> {
    let args = Args::parse();
    let plan = build_plan(&args)?;
    // Reject `chunker: ast` when the binary lacks the `ast` feature (clear, actionable
    // error). dry_run is chunker-agnostic, but validating early keeps the message at the
    // top regardless of subcommand.
    indexer::ensure_chunker_available(&plan)?;

    match &args.command {
        Some(Cmd::Flush) => {
            let backend = factory(&plan)?;
            backend.flush().await
        }
        Some(Cmd::Sync(sync_args)) => {
            let backend = factory(&plan)?;
            backend.ensure_ready(false).await?;
            sync(&backend, &plan, sync_args).await
        }
        #[cfg(feature = "mcp")]
        Some(Cmd::Mcp(mcp_args)) => run_mcp(&args, mcp_args.allow_write, mcp_args.allow_setup).await,
        #[cfg(any(feature = "duckdb", feature = "qdrant"))]
        Some(Cmd::Duplicates(dup_args)) => run_duplicates(&plan, dup_args).await,
        #[cfg(any(feature = "duckdb", feature = "qdrant"))]
        Some(Cmd::Similar(sim_args)) => run_similar(&plan, sim_args).await,
        None => {
            // Default action: full index of --root.
            if args.dry_run {
                indexer::dry_run(&plan);
                return Ok(());
            }
            let backend = factory(&plan)?;
            backend.ensure_ready(args.recreate).await?;
            if !args.query_only {
                index_sources(&backend, &plan).await?;
            }
            if let Some(q) = args.query.as_deref() {
                run_query(&backend, &plan, q).await?;
            }
            Ok(())
        }
    }
}

/// Batch size for embed+upsert. Bounds the embedder POST size (Ollama) and lets us emit
/// a live progress line without one giant call.
const UPSERT_BATCH: usize = 64;

/// Walk the root, collect chunks, and upsert them in batches (wrapped in begin/end_bulk),
/// printing a single updating progress line to stderr while embedding.
async fn index_sources(backend: &Backend, plan: &Plan) -> Result<()> {
    let (chunks, files, skipped) = indexer::collect_chunks(plan);
    let chunks_total = chunks.len();

    backend.begin_bulk().await?;
    let mut done = 0usize;
    for batch in chunks.chunks(UPSERT_BATCH) {
        backend.upsert(batch).await?;
        done += batch.len();
        // Single updating line on stderr (carriage return, no newline until the end).
        eprint!("\rembedded {done}/{chunks_total} chunks");
        let _ = std::io::Write::flush(&mut std::io::stderr());
    }
    if chunks_total > 0 {
        eprintln!();
    }
    backend.end_bulk().await?;

    println!(
        "indexed {} chunks from {} {} file(s) into '{}' ({} file(s) skipped by config)",
        chunks_total,
        files,
        plan.ext.join("/"),
        plan.collection,
        skipped
    );
    Ok(())
}

/// Outcome of re-indexing a single path: either it was removed (gone/excluded/empty,
/// with a reason) or re-indexed with N fresh chunks.
pub enum ReindexOutcome {
    /// File removed from the index. `reason` explains why (for logging only).
    Removed { reason: &'static str },
    /// File re-indexed with `chunks` fresh chunks upserted.
    Reindexed { chunks: usize },
}

/// Shared per-file re-index step used by BOTH `sync` and the MCP `refresh` tool: delete the
/// file's existing points, then — if it exists AND passes ext + globs + (not generated) —
/// chunk it (honoring `plan.chunker`), embed, and upsert. Returns what happened so callers
/// can log or report it. Caller is responsible for wrapping a batch in begin/end_bulk.
pub async fn reindex_file(backend: &Backend, plan: &Plan, rel: &str) -> Result<ReindexOutcome> {
    let key = rel.trim_start_matches("./");
    // Always remove the file's existing points first ("remove completely").
    backend.delete_by_path(key).await?;

    let path = Path::new(rel);
    let indexable =
        path.is_file() && indexer::has_wanted_ext(path, &plan.ext) && plan.passes_globs(key);
    if !indexable {
        return Ok(ReindexOutcome::Removed { reason: "removed" });
    }

    let raw = std::fs::read_to_string(path).with_context(|| format!("failed to read {key}"))?;
    if plan.skip_generated && indexer::is_generated(&raw) {
        return Ok(ReindexOutcome::Removed {
            reason: "removed: autogenerated",
        });
    }
    let file_chunks = indexer::build_chunks(plan, path, key, &raw);
    if file_chunks.is_empty() {
        return Ok(ReindexOutcome::Removed {
            reason: "removed: no indexable content",
        });
    }
    let n = file_chunks.len();
    backend.upsert(&file_chunks).await?;
    Ok(ReindexOutcome::Reindexed { chunks: n })
}

/// Re-index only changed files: delete each file's existing points, then upload the current
/// content fresh. Deleted/now-excluded files are removed from the collection.
async fn sync(backend: &Backend, plan: &Plan, sync_args: &SyncArgs) -> Result<()> {
    let changed = changed_files(sync_args)?;
    if changed.is_empty() {
        println!("sync: no changed files");
        return Ok(());
    }

    // Always wrap the loop in a bulk window. Qdrant's begin/end_bulk are no-ops, so
    // this is free there. For DuckDB it is REQUIRED for correctness: every sync does a
    // `delete_by_path`, and DuckDB's experimental HNSW index returns too few candidates
    // after in-place deletes (recall degrades — `hnsw_compact_index` does not fix it).
    // begin_bulk drops the index and end_bulk recreates it, restoring full recall.
    backend.begin_bulk().await?;

    let (mut reindexed, mut deleted, mut chunks) = (0usize, 0usize, 0usize);
    for rel in &changed {
        let key = rel.trim_start_matches("./");
        match reindex_file(backend, plan, rel).await? {
            ReindexOutcome::Removed { reason } => {
                deleted += 1;
                println!("  - {key} ({reason})");
            }
            ReindexOutcome::Reindexed { chunks: n } => {
                chunks += n;
                reindexed += 1;
                println!("  + {key} ({n} chunks)");
            }
        }
    }

    backend.end_bulk().await?;

    println!("sync: {reindexed} file(s) re-indexed ({chunks} chunks), {deleted} file(s) removed");
    Ok(())
}

/// Resolve the changed-file list from explicit args or `git diff`.
fn changed_files(sync_args: &SyncArgs) -> Result<Vec<String>> {
    if !sync_args.files.is_empty() {
        return Ok(sync_args.files.clone());
    }
    let mut cmd = Command::new("git");
    cmd.args(["diff", "--name-only"]);
    if sync_args.staged {
        cmd.arg("--cached");
    } else {
        cmd.arg(&sync_args.since);
    }
    let output = cmd
        .output()
        .context("failed to run `git diff` (is git on PATH?)")?;
    if !output.status.success() {
        anyhow::bail!(
            "git diff failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(String::from_utf8_lossy(&output.stdout)
        .lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty())
        .collect())
}

/// Run the read-only MCP server over stdio. Defaults backend=duckdb + embedder=ollama
/// (the offline, no-quota path) unless the user overrode `--backend`/`--embedder` (or set
/// them in the config). Builds the backend + embedder ONCE, opens DuckDB read-only, then
/// serves rmcp until EOF.
#[cfg(feature = "mcp")]
async fn run_mcp(args: &Args, allow_write: bool, allow_setup: bool) -> Result<()> {
    // Apply the MCP-specific defaults: when the user did not pass `--backend`/`--embedder`,
    // prefer duckdb + ollama (the indexer's global defaults are qdrant + ort). Explicit
    // CLI flags still win; config values are honored via the normal merge in `build_plan`.
    let mut mcp_args = args.clone();
    if mcp_args.backend.is_none() {
        mcp_args.backend = Some("duckdb".to_string());
    }
    if mcp_args.embedder.is_none() {
        mcp_args.embedder = Some("ollama".to_string());
    }
    let plan = build_plan(&mcp_args)?;
    indexer::ensure_chunker_available(&plan)?;
    // --allow-write opens the index WRITABLE (normal `connect`, incl. HNSW persistence) so
    // the `refresh` tool can delete + re-embed. Default is read-only: `refresh` then errors.
    let backend = if allow_write {
        let b = vectordbs::factory(&plan)?;
        b.ensure_ready(false).await?;
        b
    } else {
        vectordbs::factory_readonly(&plan)?
    };
    // The DuckDB backend is `!Send`/`!Sync` (its connection + ort session), so it cannot
    // be held across an `.await` inside an rmcp `#[tool]` handler (those futures must be
    // `Send`). Move it onto a dedicated worker thread that owns it; the MCP server holds
    // only a `Send`+`Sync` channel handle. See `worker.rs` for the full rationale.
    let can_embed_locally = plan.backend == "duckdb";
    let handle = worker::spawn(backend, plan.clone(), can_embed_locally)?;
    mcp::serve_inner(handle, &plan, allow_write, allow_setup).await
}

/// Run a semantic query and print the hits exactly as before.
async fn run_query(backend: &Backend, plan: &Plan, q: &str) -> Result<()> {
    let hits = backend.query(q, plan.limit).await?;
    println!("\ntop {} for: {q}", hits.len());
    for h in &hits {
        print_hit(h);
    }
    Ok(())
}

/// Render one hit: `score  path:start-end`.
fn print_hit(h: &Hit) {
    println!(
        "  {:.4}  {}:{}-{}",
        h.score, h.path, h.start_line, h.end_line
    );
}

/// Default cap on clusters printed by `duplicates` when `--max-clusters` is omitted.
#[cfg(any(feature = "duckdb", feature = "qdrant"))]
const DEFAULT_DUP_MAX_CLUSTERS: usize = 50;

/// `duplicates` handler: resolve each knob (CLI flag > config > built-in default), open the
/// index read-only, run the shared codebase-wide near-duplicate scan, and print the clusters
/// human-readably.
#[cfg(any(feature = "duckdb", feature = "qdrant"))]
async fn run_duplicates(plan: &Plan, args: &DuplicatesArgs) -> Result<()> {
    // Knob resolution: CLI flag > config (similarity.*) > built-in default.
    let min_score = args.min_score.unwrap_or_else(|| plan.duplicate_min_score());
    let min_cluster_size = args
        .min_cluster_size
        .unwrap_or_else(|| plan.duplicate_min_cluster_size())
        .max(1);
    let top_k = args.top_k.unwrap_or_else(|| plan.top_k() as u64);
    let max_clusters = args.max_clusters.unwrap_or(DEFAULT_DUP_MAX_CLUSTERS);

    let backend = vectordbs::factory_readonly(plan)?;
    let clusters = search::find_duplicates(
        &backend,
        min_score,
        min_cluster_size,
        top_k,
        max_clusters,
        args.path_glob.as_deref(),
    )
    .await?;

    if clusters.is_empty() {
        println!(
            "no near-duplicate clusters (min_score {min_score}, min_cluster_size {min_cluster_size}, top_k {top_k})"
        );
        return Ok(());
    }
    println!(
        "{} near-duplicate cluster(s) (min_score {min_score}, min_cluster_size {min_cluster_size}, top_k {top_k}):",
        clusters.len()
    );
    for c in &clusters {
        println!(
            "cluster (size {}, sim {:.4}..{:.4}):",
            c.size, c.min_sim, c.max_sim
        );
        for m in &c.members {
            let symbol = m.symbol.as_deref().unwrap_or("");
            println!("  {}:{}-{}  {}", m.path, m.start_line, m.end_line, symbol);
        }
    }
    Ok(())
}

/// `similar` handler: require EXACTLY ONE of --code or (--path & --line), resolve min_score
/// (flag > config.find_similar_min_score > default), open the index read-only, run the shared
/// nearest-neighbour resolution, and print `score  path:start-end  symbol`.
#[cfg(any(feature = "duckdb", feature = "qdrant"))]
async fn run_similar(plan: &Plan, args: &SimilarArgs) -> Result<()> {
    use search::SimilarTarget;

    // Require exactly one of --code or (--path AND --line).
    let target = match (args.code.as_deref(), args.path.as_deref(), args.line) {
        (Some(_), Some(_), _) | (Some(_), _, Some(_)) => {
            anyhow::bail!("similar: provide EITHER --code OR (--path and --line), not both");
        }
        (Some(code), None, None) => SimilarTarget::Code(code),
        (None, Some(path), Some(line)) => SimilarTarget::Location { path, line },
        (None, Some(_), None) | (None, None, Some(_)) => {
            anyhow::bail!("similar: --path and --line must be given together");
        }
        (None, None, None) => {
            anyhow::bail!("similar: provide either --code or both --path and --line");
        }
    };

    let min_score = args
        .min_score
        .unwrap_or_else(|| plan.find_similar_min_score());

    let backend = vectordbs::factory_readonly(plan)?;
    let hits = search::find_similar(&backend, target, args.limit, min_score).await?;

    println!("{} similar (min_score {min_score}):", hits.len());
    for h in &hits {
        let symbol = h.symbol.as_deref().unwrap_or("");
        println!(
            "  {:.4}  {}:{}-{}  {}",
            h.score, h.path, h.start_line, h.end_line, symbol
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    //! Happy-path flow tests driving the REAL orchestration fns (`index_sources`,
    //! `sync`, `run_query`, `flush`) against the in-memory [`MockBackend`]. No
    //! network, no real Qdrant/DuckDB: every call is recorded by the mock and
    //! asserted here. Source trees are built under a `tempdir`.

    use super::*;
    use crate::vectordbs::mock::{MockBackend, MockCalls};
    use globset::GlobSetBuilder;
    use std::collections::HashSet;
    use std::fs;
    use std::sync::MutexGuard;
    use tempfile::TempDir;

    /// Lock and return the recorded calls of a `Backend::Mock`. Every flow test
    /// here builds a `Mock` backend, so any other variant is a test-harness bug.
    fn mock_calls(backend: &Backend) -> MutexGuard<'_, MockCalls> {
        match backend {
            Backend::Mock(m) => m.calls.lock().unwrap(),
            #[allow(unreachable_patterns)]
            _ => unreachable!("flow tests only use Backend::Mock"),
        }
    }

    /// Build a minimal `Plan` rooted at `root` with `ext` = ts and no globs. Mirrors
    /// `build_plan` defaults without reading any YAML.
    fn test_plan(root: &str) -> Plan {
        let empty = GlobSetBuilder::new().build().expect("empty globset");
        Plan {
            root: root.to_string(),
            ext: vec!["ts".to_string()],
            language: "ts".to_string(),
            backend: "mock".to_string(),
            embedder: "ort".to_string(),
            chunker: "lines".to_string(),
            max_chunk_chars: 1400,
            prefix_style: crate::vectordbs::PrefixStyle::E5,
            collection: "test_coll".to_string(),
            model: "intfloat/multilingual-e5-small".to_string(),
            vector_dim: 384,
            duckdb_path: ".index/code.duckdb".to_string(),
            duckdb_model_cache: None,
            model_repo: "Xenova/multilingual-e5-small".to_string(),
            ollama_url: "http://localhost:11434".to_string(),
            ollama_model: None,
            exclude_dirs: HashSet::new(),
            include: GlobSetBuilder::new().build().expect("include globset"),
            include_active: false,
            exclude: empty,
            skip_generated: true,
            strip_comments: true,
            limit: 5,
            find_similar_min_score: 0.85,
            duplicate_min_score: 0.93,
            duplicate_min_cluster_size: 2,
            top_k: 10,
        }
    }

    /// A plan whose `exclude` globset drops `**/*.test.ts`.
    fn test_plan_excluding_tests(root: &str) -> Plan {
        let mut b = GlobSetBuilder::new();
        b.add(globset::Glob::new("**/*.test.ts").unwrap());
        let mut plan = test_plan(root);
        plan.exclude = b.build().expect("exclude globset");
        plan
    }

    /// index: begin_bulk → upsert(N) → end_bulk, and the upserted count equals
    /// what `collect_chunks` produces from the temp tree.
    #[tokio::test]
    async fn index_drives_begin_upsert_end_in_order() {
        let dir = TempDir::new().unwrap();
        let root = dir.path().to_string_lossy().to_string();
        fs::write(
            dir.path().join("alpha.ts"),
            "export function alpha() { return 1 }\nconst x = alpha()\n",
        )
        .unwrap();
        fs::write(
            dir.path().join("beta.ts"),
            "export const beta = () => 2\nconsole.log(beta())\n",
        )
        .unwrap();

        let plan = test_plan(&root);
        let (expected_chunks, _, _) = indexer::collect_chunks(&plan);
        let expected = expected_chunks.len();
        assert!(expected > 0, "fixture must produce chunks");

        let backend = Backend::Mock(MockBackend::new());
        index_sources(&backend, &plan).await.unwrap();

        let calls = mock_calls(&backend);
        assert_eq!(calls.begin_bulk, 1, "exactly one begin_bulk");
        assert_eq!(calls.end_bulk, 1, "exactly one end_bulk");
        assert_eq!(calls.upserts.len(), 1, "one upsert batch");
        assert_eq!(
            calls.total_upserted_chunks(),
            expected,
            "upserted chunk count must match collect_chunks"
        );
    }

    /// sync (explicit --file list, no git): an indexable file, an excluded test
    /// file, and a deleted/non-existent path. delete_by_path fires for EACH
    /// changed path; the loop is wrapped by begin/end_bulk; only the indexable
    /// file yields an upsert.
    #[tokio::test]
    async fn sync_deletes_every_path_and_upserts_only_indexable() {
        let dir = TempDir::new().unwrap();
        let root = dir.path().to_string_lossy().to_string();
        let good = dir.path().join("keep.ts");
        let excluded = dir.path().join("keep.test.ts");
        fs::write(&good, "export function keep() { return 42 }\n").unwrap();
        fs::write(&excluded, "export const t = 1\n").unwrap();
        let gone = dir.path().join("gone.ts"); // never created → deleted path

        let plan = test_plan_excluding_tests(&root);
        let sync_args = SyncArgs {
            since: "HEAD~1".to_string(),
            staged: false,
            files: vec![
                good.to_string_lossy().to_string(),
                excluded.to_string_lossy().to_string(),
                gone.to_string_lossy().to_string(),
            ],
        };

        let backend = Backend::Mock(MockBackend::new());
        sync(&backend, &plan, &sync_args).await.unwrap();

        let calls = mock_calls(&backend);
        // delete_by_path called once per changed path (3).
        assert_eq!(calls.deletes.len(), 3, "delete fired for each changed path");
        // begin/end_bulk wrap the loop.
        assert_eq!(calls.begin_bulk, 1);
        assert_eq!(calls.end_bulk, 1);
        // Only the indexable (non-test, existing) file produced an upsert.
        assert_eq!(calls.upserts.len(), 1, "only the indexable file upserts");
        assert!(calls.upserts[0].count > 0, "indexable file produced chunks");
    }

    /// flush: orchestration invokes backend.flush().
    #[tokio::test]
    async fn flush_invokes_backend_flush() {
        let backend = Backend::Mock(MockBackend::new());
        backend.flush().await.unwrap();
        let calls = mock_calls(&backend);
        assert_eq!(calls.flush, 1, "flush called exactly once");
    }

    /// reindex_file (the shared helper used by both `sync` and the MCP `refresh` tool):
    /// an existing indexable file deletes-then-upserts and reports its chunk count; a
    /// gone/excluded path deletes-only and reports Removed.
    #[tokio::test]
    async fn reindex_file_reindexes_existing_and_removes_gone() {
        let dir = TempDir::new().unwrap();
        let root = dir.path().to_string_lossy().to_string();
        let good = dir.path().join("keep.ts");
        fs::write(&good, "export function keep() { return 42 }\n").unwrap();
        let gone = dir.path().join("gone.ts"); // never created

        let plan = test_plan(&root);
        let backend = Backend::Mock(MockBackend::new());

        let good_path = good.to_string_lossy().to_string();
        match reindex_file(&backend, &plan, &good_path).await.unwrap() {
            ReindexOutcome::Reindexed { chunks } => assert!(chunks > 0, "indexable file chunks"),
            ReindexOutcome::Removed { .. } => panic!("existing file must be reindexed"),
        }
        let gone_path = gone.to_string_lossy().to_string();
        match reindex_file(&backend, &plan, &gone_path).await.unwrap() {
            ReindexOutcome::Removed { .. } => {}
            ReindexOutcome::Reindexed { .. } => panic!("gone file must be removed"),
        }

        let calls = mock_calls(&backend);
        // delete fired for BOTH paths; only the existing file produced an upsert.
        assert_eq!(calls.deletes.len(), 2, "delete fires per path");
        assert_eq!(calls.upserts.len(), 1, "only the existing file upserts");
    }

    /// Threshold resolution: a Plan built with no `similarity:` config yields the
    /// built-in defaults via the accessor methods (the MCP tools read these when the
    /// tool arg is omitted). Tool arg > config > default — here only the default rung.
    #[test]
    fn similarity_defaults_resolve() {
        let plan = crate::config::test_support::minimal_plan();
        assert_eq!(plan.find_similar_min_score(), 0.85);
        assert_eq!(plan.duplicate_min_score(), 0.93);
        assert_eq!(plan.duplicate_min_cluster_size(), 2);
        assert_eq!(plan.top_k(), 10);
    }

    /// query: run_query issues the query and renders the canned hits.
    #[tokio::test]
    async fn query_runs_and_returns_canned_hits() {
        let dir = TempDir::new().unwrap();
        let plan = test_plan(&dir.path().to_string_lossy());
        let backend = Backend::Mock(MockBackend::new());

        // run_query renders to stdout; assert it completes and recorded the query.
        run_query(&backend, &plan, "where is alpha").await.unwrap();
        // Independently confirm the canned result set is deterministic.
        let hits = backend.query("where is alpha", plan.limit).await.unwrap();

        let calls = mock_calls(&backend);
        assert_eq!(calls.queries.len(), 2, "run_query + direct query");
        assert_eq!(calls.queries[0], "where is alpha");
        assert_eq!(hits.len(), 2, "canned hits returned");
        assert_eq!(hits[0].path, "src/alpha.ts");
        assert!(hits[0].score >= hits[1].score, "hits ordered by score");
    }
}
