//! [`MockStore`]: a `#[cfg(test)]` [`VectorStore`] over the existing in-memory
//! [`MockBackend`], so service unit tests (US-003) can run fully in-process — NO worker
//! thread, NO network. A trivial newtype delegation, like [`crate::repos::qdrant`]; the
//! impl is generated by [`impl_vectorstore_delegate!`](crate::repos::delegate).

use crate::repos::delegate::impl_vectorstore_delegate;
use crate::vectordbs::mock::MockBackend;

/// Newtype adapter wrapping the in-memory [`MockBackend`].
pub struct MockStore(pub MockBackend);

impl_vectorstore_delegate!(MockStore);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::repos::VectorStore;
    use crate::vectordbs::mock::MockRow;

    /// In-process round-trip through the trait (NO worker thread, NO network): a seeded
    /// `MockStore` returns its canned `query` hits and ranks seeded rows by `query_by_vector`.
    /// Proves the `VectorStore` trait + the in-process mock path that the services will use.
    #[tokio::test]
    async fn mock_store_round_trips_query_and_query_by_vector() {
        // `query` returns the backend's two canned hits (alpha, beta), in order.
        let store: &dyn VectorStore = &MockStore(MockBackend::new());
        let hits = store.query("anything", 10).await.unwrap();
        assert_eq!(hits.len(), 2);
        assert_eq!(hits[0].path, "src/alpha.ts");
        assert_eq!(hits[1].path, "src/beta.ts");

        // `query_by_vector` ranks the seeded rows by cosine to the probe; the row whose
        // vector equals the probe ranks first, and self-exclusion drops it by id.
        let rows = vec![
            MockRow::new(1, "src/one.ts", 1, vec![1.0, 0.0, 0.0, 0.0]),
            MockRow::new(2, "src/two.ts", 1, vec![0.0, 1.0, 0.0, 0.0]),
        ];
        let store = MockStore(MockBackend::with_rows(rows));
        let ranked = store
            .query_by_vector(&[1.0, 0.0, 0.0, 0.0], 10, None)
            .await
            .unwrap();
        assert_eq!(
            ranked.first().map(|h| h.id),
            Some(1),
            "closest row ranks first"
        );

        let excluded = store
            .query_by_vector(&[1.0, 0.0, 0.0, 0.0], 10, Some(1))
            .await
            .unwrap();
        assert!(
            excluded.iter().all(|h| h.id != 1),
            "exclude_id drops the self row"
        );
    }
}
