//! [`QdrantStore`]: the [`VectorStore`] adapter over the existing, unchanged
//! [`QdrantBackend`]. `QdrantBackend` is already `Send + Sync` (the `qdrant_client`
//! channel is), so this is a TRIVIAL newtype: the impl is generated by
//! [`impl_vectorstore_delegate!`](crate::repos::delegate), forwarding every method to the
//! inner backend's same-named inherent method. Behavior is preserved exactly — in
//! particular `embed_query`/`embed_passage` bail in server mode just as the backend does.

use crate::repos::delegate::impl_vectorstore_delegate;
use crate::vectordbs::qdrant::QdrantBackend;

/// Newtype adapter wrapping the existing [`QdrantBackend`].
pub struct QdrantStore(pub QdrantBackend);

impl_vectorstore_delegate!(QdrantStore);
